import {digestCanonical,verifySelfHash} from './canonical-json.mjs';import {check} from './lib.mjs';import {R10_POINTER_ID,R10_POINTER_SCHEMA_VERSION,R10_RELEASE_PROFILE_ID} from './identity.mjs';
export function pointerSelfHash(doc){const x={...doc};delete x.pointerSha256;return digestCanonical(x);}
export function sealPointer(doc){const x={...doc};delete x.pointerSha256;return {...x,pointerSha256:digestCanonical(x)};}
export function validateV2(p){check(p?.schemaVersion===2&&p?.pointerId===R10_POINTER_ID,'E_R10_POINTER_SCHEMA_INVALID','invalid v2 pointer');check(p.rollbackUnit==='whole-build-only'&&p.legacyFallbackAllowed===false&&p.perEncoderRollbackAllowed===false,'E_R10_POINTER_SCHEMA_INVALID','unsafe v2 pointer');return p;}
export function upgradeV2(p){validateV2(p);return sealPointer({schemaVersion:3,pointerId:R10_POINTER_ID,generation:0,activeBuildId:p.activeBuildId??null,activePackageContentId:p.activePackageContentId??null,activeReleaseProfileId:p.activeReleaseProfileId??null,activeQualificationReceipts:{},previousBuildId:p.previousBuildId??null,previousPackageContentId:p.previousPackageContentId??null,previousReleaseProfileId:null,previousQualificationReceipts:{},candidateBuildId:p.candidateBuildId??null,candidatePackageContentId:p.candidatePackageContentId??null,candidateReleaseProfileId:p.candidateReleaseProfileId??null,candidateQualificationReceipts:null,lastTransitionId:null,lastTransitionKind:null,lastTransitionIntentSha256:null,rollbackUnit:'whole-build-only',legacyFallbackAllowed:false,perEncoderRollbackAllowed:false,perKernelRollbackAllowed:false,pointerMutationPerformed:false});}
export function readCompatiblePointer(p){return p?.schemaVersion===2?upgradeV2(p):validateV3(p);}
export function validateV3(p){check(p?.schemaVersion===R10_POINTER_SCHEMA_VERSION&&p?.pointerId===R10_POINTER_ID,'E_R10_POINTER_SCHEMA_INVALID','invalid pointer v3');check(Number.isSafeInteger(p.generation)&&p.generation>=0,'E_R10_POINTER_GENERATION_MISMATCH','invalid generation');check(p.rollbackUnit==='whole-build-only'&&p.legacyFallbackAllowed===false&&p.perEncoderRollbackAllowed===false&&p.perKernelRollbackAllowed===false,'E_R10_PARTIAL_ROLLBACK_FORBIDDEN','unsafe rollback policy');check(p.pointerSha256===pointerSelfHash(p),'E_R10_POINTER_SELF_HASH_MISMATCH','pointer self hash mismatch');return p;}
export function qualificationMap(candidate){return {'tdt.export.full-product':candidate.fullProductReceiptSha256,'tdt.resample-runtime':candidate.r9FinalReceiptSha256};}
export function transitionPointer(current,intent,candidate,kind){validateV3(current);check(['PROMOTE','ROLLBACK','REPROMOTE'].includes(kind),'E_R10_POINTER_SCHEMA_INVALID','invalid transition kind');check(intent.expectedGeneration===current.generation,'E_R10_POINTER_GENERATION_MISMATCH','intent generation mismatch');const target=kind==='ROLLBACK'?candidate.previous:candidate.target;check(target?.buildId&&target?.packageContentId,'E_R10_ROLLBACK_TARGET_MISSING','target identity missing');const currentSource={buildId:current.activeBuildId,packageContentId:current.activePackageContentId,releaseProfileId:current.activeReleaseProfileId,qualificationReceipts:current.activeQualificationReceipts||{}};const source=(kind==='PROMOTE'&&current.activeBuildId===null&&candidate.previous)?candidate.previous:currentSource;return sealPointer({schemaVersion:3,pointerId:R10_POINTER_ID,generation:current.generation+1,activeBuildId:target.buildId,activePackageContentId:target.packageContentId,activeReleaseProfileId:target.releaseProfileId||R10_RELEASE_PROFILE_ID,activeQualificationReceipts:target.qualificationReceipts||{},previousBuildId:source.buildId,previousPackageContentId:source.packageContentId,previousReleaseProfileId:source.releaseProfileId,previousQualificationReceipts:source.qualificationReceipts||{},candidateBuildId:null,candidatePackageContentId:null,candidateReleaseProfileId:null,candidateQualificationReceipts:null,lastTransitionId:intent.transitionId,lastTransitionKind:kind,lastTransitionIntentSha256:intent.intentSha256,rollbackUnit:'whole-build-only',legacyFallbackAllowed:false,perEncoderRollbackAllowed:false,perKernelRollbackAllowed:false,pointerMutationPerformed:true});}
