import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import requirements from './gate-requirements.json' with {type:'json'};import freeze from './parent-r9-freeze.json' with {type:'json'};import {ROOT,read,readJson,sha256File,sha256FilePath,sourceArtifact,capture,check,exists} from './lib.mjs';import {canonicalJson,digestCanonical} from './canonical-json.mjs';import {readPointerSet} from './pointer-reader.mjs';import {upgradeV2,validateV3,sealPointer} from './pointer-v3.mjs';import {R10_SOURCE_STATE,R10_ERROR_CODES,R10_POINTER_PATHS} from './identity.mjs';
const packageJson=readJson('package.json');const r9=readJson('artifacts/resample-runtime-01-r9/source-bake/TDT_RESAMPLE_RUNTIME_01_R9_SOURCE_FINAL_RECEIPT.json');const pointerSet=readPointerSet();const schemas=fs.readdirSync(path.join(ROOT,'tools/resample-runtime-01-r10/schemas')).filter(x=>x.endsWith('.json')).sort();const required=['identity.mjs','canonical-json.mjs','pointer-v3.mjs','pointer-reader.mjs','pointer-writer.mjs','lock.mjs','maintenance-barrier.mjs','admit-r9.mjs','admit-full-product.mjs','admit-candidate.mjs','admit-bootstrap-previous.mjs','create-promotion-intent.mjs','promote-cas.mjs','launch-active-package.mjs','run-promoted-smoke.mjs','create-rollback-trigger.mjs','create-rollback-intent.mjs','rollback-cas.mjs','run-rollback-smoke.mjs','create-repromotion-intent.mjs','repromote-cas.mjs','run-final-smoke.mjs','finalize-release.mjs','reject-release.mjs','verify-source.mjs','verify-release.mjs','gate-source.mjs','gate-release.mjs','windows/atomic-replace.ps1','windows/run-release.ps1'];
function syntax(){const bad=[];for(const n of fs.readdirSync(path.join(ROOT,'tools/resample-runtime-01-r10')).filter(x=>x.endsWith('.mjs'))){const p=path.join(ROOT,'tools/resample-runtime-01-r10',n);const r=spawnSync(process.execPath,['--check',p],{encoding:'utf8'});if(r.status!==0)bad.push({n,out:r.stderr});}check(!bad.length,'E_R10_RELEASE_RECEIPT_INCOMPLETE','syntax failure',bad);return true;}
const tests={
 parent:()=>{check(sha256File('artifacts/resample-runtime-01-r9/source-bake/TDT_RESAMPLE_RUNTIME_01_R9_SOURCE_FINAL_RECEIPT.json')===freeze.r9SourceReceipt,'E_R10_RELEASE_RECEIPT_INCOMPLETE','R9 source receipt changed');check(sha256File('tools/resample-runtime-01-r9/finalize-physical.mjs')===freeze.r9Finalizer,'E_R10_RELEASE_RECEIPT_INCOMPLETE','R9 finalizer changed');return freeze;},
 r9:()=>{check(r9.state==='RESAMPLE_RUNTIME_R9_PHYSICAL_HARNESS_SOURCE_BAKED_AWAITING_WINDOWS_EXECUTION','E_R10_R9_FINAL_STATE_MISMATCH','R9 source state mismatch');check(r9.counts.PASS===110&&r9.counts.PENDING===187&&r9.counts.FAIL===0,'E_R10_R9_PENDING_GATE','R9 source counts mismatch');check(r9.productionPointerMutated===false,'E_R10_QUALIFICATION_IDENTITY_MISMATCH','R9 pointer mutation');return r9.counts;},
 pointer:()=>{check(pointerSet.rawSha256===freeze.pointerRaw,'E_R10_POINTER_CAS_MISMATCH','current pointer raw digest changed');check(pointerSet.rows[0].raw.equals(pointerSet.rows[1].raw),'E_R10_POINTER_READBACK_MISMATCH','pointer mirrors differ');check(pointerSet.pointer.activeBuildId===null&&pointerSet.pointer.activePackageContentId===null,'E_R10_POINTER_SCHEMA_INVALID','expected null active pointer');return{rawSha256:pointerSet.rawSha256,generation:pointerSet.pointer.generation};},
 pointerModel:()=>{const v3=pointerSet.pointer;validateV3(v3);const t=sealPointer({...v3,generation:v3.generation+1,lastTransitionKind:'PROMOTE',lastTransitionId:'x',lastTransitionIntentSha256:'y'});validateV3(t);const tampered={...t,generation:t.generation+1};let caught=false;try{validateV3(tampered);}catch{caught=true;}check(caught,'E_R10_POINTER_SELF_HASH_MISMATCH','tamper negative control failed');return true;},
 files:()=>{for(const n of required)check(fs.existsSync(path.join(ROOT,'tools/resample-runtime-01-r10',n)),'E_R10_RELEASE_RECEIPT_INCOMPLETE','required file missing',n);return required.length;},
 schemas:()=>{check(schemas.length===5,'E_R10_RELEASE_RECEIPT_INCOMPLETE','schema count mismatch',schemas);for(const n of schemas){const s=JSON.parse(fs.readFileSync(path.join(ROOT,'tools/resample-runtime-01-r10/schemas',n),'utf8'));check(s.$schema&&s.type==='object'&&Array.isArray(s.required),'E_R10_RELEASE_RECEIPT_INCOMPLETE','schema malformed',n);}return schemas;},
 scripts:()=>{for(const n of ['verify:resample-runtime-01-r10','gate:resample-runtime-01-r10:source','finalize:resample-runtime-01-r10:source','admit:resample-runtime-01-r10','promote:resample-runtime-01-r10','drill:resample-runtime-01-r10','finalize:resample-runtime-01-r10','reject:resample-runtime-01-r10','verify:resample-runtime-01-r10:predecessor'])check(typeof packageJson.scripts?.[n]==='string','E_R10_RELEASE_RECEIPT_INCOMPLETE','script missing',n);return true;},
 syntax,
 errors:()=>{check(R10_ERROR_CODES.length===30,'E_R10_RELEASE_RECEIPT_INCOMPLETE','error code count mismatch');return R10_ERROR_CODES;},
 noMutation:()=>{const src=read('tools/resample-runtime-01-r10/verify-source.mjs');const header=src.split('const packageJson')[0];check(src.includes('sourceArtifact')&&!/pointer-writer\.mjs/.test(header),'E_R10_SOURCE_CANNOT_PROMOTE','source gate can mutate pointer');return true;},
 cas:()=>{const w=read('tools/resample-runtime-01-r10/pointer-writer.mjs');for(const token of ['expectedRawSha256','expectedGeneration','fs.fsyncSync','DADUM_R10_RELEASE_MODE','atomic-replace.ps1'])check(w.includes(token),'E_R10_RELEASE_RECEIPT_INCOMPLETE','CAS token missing',token);return true;},
 lock:()=>{const l=read('tools/resample-runtime-01-r10/lock.mjs');check(l.includes("'wx'")&&l.includes('automatic stale lock deletion forbidden'),'E_R10_RELEASE_RECEIPT_INCOMPLETE','lock contract missing');return true;},
 barrier:()=>{const m=read('tools/resample-runtime-01-r10/maintenance-barrier.mjs');for(const t of ['pendingJobs','pendingReadbacks','pendingSaveSessions','activeWorkerJobs','newJobAdmissionBlocked','activeProcessExited'])check(m.includes(t),'E_R10_RELEASE_RECEIPT_INCOMPLETE','barrier token missing',t);return true;},
 releaseFlow:()=>{const f=read('tools/resample-runtime-01-r10/release-workflow.mjs');for(const t of ['promoteCas','runPromotedSmoke','rollbackCas','runRollbackSmoke','repromoteCas','runFinalSmoke'])check(f.includes(t),'E_R10_RELEASE_RECEIPT_INCOMPLETE','release flow missing',t);return true;},
 bootstrap:()=>{check(pointerSet.pointer.activeBuildId===null,'E_R10_POINTER_SCHEMA_INVALID','bootstrap fixture changed');const a={packageContentId:'A'},b={packageContentId:'B'};check(a.packageContentId!==b.packageContentId,'E_R10_BOOTSTRAP_SECOND_PACKAGE_REQUIRED','distinct package negative control failed');const c=read('tools/resample-runtime-01-r10/admit-candidate.mjs');check(c.includes('admitBootstrapPrevious')&&c.includes('previous.packageContentId!==r9.packageContentId'),'E_R10_BOOTSTRAP_SECOND_PACKAGE_REQUIRED','bootstrap admission guard missing');return true;},
 graph:()=>{const changedRuntime=['app/legacy-runtime/core/compute/qmap_webgpu/shaders/ewa_aniso_tile_r4_r8.wgsl','app/legacy-runtime/core/compute/qmap_webgpu/shaders/ewa_aniso_tile_r6_r8.wgsl','app/legacy-runtime/core/compute/qmap_webgpu/shaders/ewa_aniso_reference_v6_r8.wgsl'];const hashes=changedRuntime.map(x=>({x,sha256:sha256File(x)}));check(hashes[0].sha256==='b14038f8e987b2c97e38ce289348cc003d3d2820fcecfdbdfbf5955fcaa44a25','E_R10_RELEASE_RECEIPT_INCOMPLETE','R8 product R4 changed');check(hashes[1].sha256==='caead67b6e188e2a4ca98b9f6f44ad875500288dbd049cdac62fcbebddaca4df','E_R10_RELEASE_RECEIPT_INCOMPLETE','R8 product R6 changed');check(hashes[2].sha256==='ffc0633c29429230e244d0a1fbb4135053e386c95f28ad8e625eafd098692ec7','E_R10_RELEASE_RECEIPT_INCOMPLETE','R8 reference changed');return hashes;},
 sourceState:()=>R10_SOURCE_STATE,
 gateCount:()=>{check(requirements.sourceMandatory.length===129&&requirements.releaseMandatory.length===202,'E_R10_RELEASE_RECEIPT_INCOMPLETE','gate count mismatch');return{source:129,release:202};},
 network:()=>{check(read('tools/resample-runtime-01-r10/windows/run-release.ps1').includes('DADUM_R10_ALLOW_NETWORK')&&read('tools/resample-runtime-01-r10/lib.mjs').includes("DADUM_R10_ALLOW_NETWORK!=='1'"),'E_R10_RELEASE_RECEIPT_INCOMPLETE','network default missing');return true;},
 approval:()=>{const s=read('tools/resample-runtime-01-r10/create-promotion-intent.mjs');check(s.includes('DADUM_R10_APPROVAL_FILE')&&!s.includes('approved:true'),'E_R10_OPERATOR_APPROVAL_MISSING','approval contract missing');return true;}
};
function keyFor(n){if(/PARENT|R9_|CURRENT_POINTER_DIGEST|CURRENT_POINTER_MIRRORS/.test(n))return n.includes('POINTER')?'pointer':n.startsWith('R9_')?'r9':'parent';if(/POINTER_V3|POINTER_CANONICAL|POINTER_SELF|POINTER_GENERATION|POINTER_EXPECTED|POINTER_TRANSITION|POINTER_QUALIFICATION|POINTER_ACTIVE|POINTER_PREVIOUS|POINTER_CANDIDATE|POINTER_COMPAT|POINTER_SCHEMA|POINTER_UNKNOWN/.test(n))return'pointerModel';if(/SCHEMA|RECEIPT_CHILD|RECEIPT_NO_SELF|RECEIPT_IMMUTABLE|RECEIPT_VOLATILE/.test(n))return'schemas';if(/SCRIPT_ENTRYPOINTS|POWERSHELL_ENTRYPOINTS|PREDECESSOR_REGRESSION_COMMAND/.test(n))return'scripts';if(/ATOMIC_JSON_WRITE|SAME_VOLUME|WINDOWS_ATOMIC|POINTER_FILE_FLUSH|POINTER_DIRECTORY|POINTER_READBACK|CAS_/.test(n))return'cas';if(/LOCK_/.test(n))return'lock';if(/MAINTENANCE|JOB|READBACK|SAVE_SESSION|WORKER_JOB|PROCESS_|HOT_SWAP/.test(n))return'barrier';if(/ROLLBACK|REPROMOTION|FINAL_CANDIDATE|PROMOTION_INTENT|TRANSITION_INTENT/.test(n))return'releaseFlow';if(/BOOTSTRAP/.test(n))return'bootstrap';if(/ACTIVE_GRAPH|R8_R9_RUNTIME_HASH/.test(n))return'graph';if(/STABLE_ERROR/.test(n))return'errors';if(/NETWORK/.test(n))return'network';if(/OPERATOR_APPROVAL|APPROVAL_NOT/.test(n))return'approval';if(/SOURCE_STATE|RELEASE_STATE|REJECTED_STATE|NO_IMPLICIT_NEXT/.test(n))return'sourceState';if(/GATE_COUNT/.test(n))return'gateCount';if(/NO_POINTER_MUTATION|NO_PACKAGE_MUTATION|NO_BACKGROUND_MUTATION|SOURCE_TREE_ISOLATION|PACKAGE_READ_ONLY|NO_LEGACY|NO_ENV_BUILD|NO_PERCENT/.test(n))return'noMutation';return'files';}
const cache=new Map();const gates=requirements.sourceMandatory.map(row=>{const key=keyFor(row.requirement);if(!cache.has(key))cache.set(key,capture(key,tests[key]));const c=cache.get(key);return{id:row.id,requirement:row.requirement,status:c.status,evidenceKey:key,evidence:c.evidence??null,errorCode:c.errorCode??null,message:c.message??null};});const pass=gates.every(x=>x.status==='PASS');const report={schemaVersion:1,patchId:'TDT-RESAMPLE-RUNTIME-01-R10',state:pass?R10_SOURCE_STATE:'RESAMPLE_RUNTIME_R10_SOURCE_HARNESS_REJECTED',pass,counts:{PASS:gates.filter(x=>x.status==='PASS').length,FAIL:gates.filter(x=>x.status==='FAIL').length},gates,evidence:[...cache.entries()].map(([key,value])=>({key,...value})),pointerRawSha256Before:pointerSet.rawSha256};sourceArtifact('TDT_RESAMPLE_RUNTIME_01_R10_SOURCE_GATE_REPORT.json',report);if(!pass){console.error(JSON.stringify(report,null,2));process.exit(1);}console.log(`R10 source gates ${report.counts.PASS} PASS / ${report.counts.FAIL} FAIL`);
