import {write,f32bits,sha256,canonical} from './lib.mjs';
const checks=[];const c=(name,pass,detail='')=>checks.push({name,pass:Boolean(pass),detail});const eps=1e-6;
const norm=(v)=>{const n=Math.hypot(v[0],v[1]);return n>eps?[v[0]/n,v[1]/n]:null;};
const axialFromTangent=(t)=>{const n=norm(t);return n?[n[0]*n[0]-n[1]*n[1],2*n[0]*n[1]]:null;};
function project(x,y,layout,samples){const gx=(x-(layout.windowWidth-1)/2)/layout.strideX,gy=(y-(layout.windowHeight-1)/2)/layout.strideY,bx=Math.floor(gx),by=Math.floor(gy);let vx=0,vy=0,wc=0,ws=0,count=0;for(let iy=0;iy<2;iy++)for(let ix=0;ix<2;ix++){const xx=bx+ix,yy=by+iy;if(xx<0||yy<0||xx>=layout.gridWidth||yy>=layout.gridHeight)continue;const ox=xx*layout.strideX,oy=yy*layout.strideY;if(x<ox||y<oy||x>ox+layout.windowWidth-1||y>oy+layout.windowHeight-1)continue;const cx=ox+(layout.windowWidth-1)/2,cy=oy+(layout.windowHeight-1)/2;const wx=Math.max(0,1-Math.abs(x-cx)/((layout.windowWidth+1)/2)),wy=Math.max(0,1-Math.abs(y-cy)/((layout.windowHeight+1)/2)),w=wx*wy;const s=samples[yy*layout.gridWidth+xx],q=norm(s.slice(0,2)),conf=Math.max(0,Math.min(1,s[3]));if(!q||!Number.isFinite(w)||w<=0||conf<=0)continue;vx+=q[0]*w*conf;vy+=q[1]*w*conf;wc+=w*conf;ws+=w;count++;}const q=norm([vx,vy]);return q&&count&&ws>eps?[q[0],q[1],wc/ws,1]:[0,0,0,0];}
function align(t,s,phase=1,phaseWeight=0){const tn=norm(t.slice(0,2)),sn=norm(s.slice(0,2));const tc=Math.max(0,Math.min(1,t[2])),sc=Math.max(0,Math.min(1,s[2]));if(!tn||!sn||tc<=0||sc<=0||s[3]<=0)return[0,0,0,0];const qt=[tn[0]*tn[0]-tn[1]*tn[1],2*tn[0]*tn[1]],d=Math.max(-1,Math.min(1,qt[0]*sn[0]+qt[1]*sn[1])),a=.5*(d+1),conf=tc*sc*((1-phaseWeight)+phaseWeight*Math.max(0,Math.min(1,phase)));return conf>0?[a,d,conf,1]:[0,0,0,0];}
function gate(a,p={enabled:true,strength:.15,minMultiplier:.85}){if(!p.enabled||p.strength===0||a[3]<=0||a[2]<=0)return[1,0,0,0];return[Math.max(p.minMultiplier,Math.min(1,1-p.strength*a[2]*(1-a[0]))),a[0],a[2],1];}
let a=align([1,0,1,1],[1,0,1,1]);c('aligned-alignment',a[0]===1,String(a));c('aligned-gate',gate(a)[0]===1,String(gate(a)));
a=align([1,0,1,1],[-1,0,1,1]);c('orthogonal-alignment',a[0]===0,String(a));c('orthogonal-gate',Math.abs(gate(a)[0]-.85)<1e-7,String(gate(a)));
c('tensor-sign-flip',JSON.stringify(align([-1,0,1,1],[1,0,1,1]))===JSON.stringify(align([1,0,1,1],[1,0,1,1])),'invariant');c('spectral-tangent-sign-flip',JSON.stringify(axialFromTangent([-1,0]))===JSON.stringify(axialFromTangent([1,0])),'double-angle invariant');c('orthogonal-double-angle-distinct',align([1,0,1,1],[-1,0,1,1])[0]===0,'orthogonal director');
const neutral=gate([0,0,0,0]);c('invalid-neutral',JSON.stringify(neutral)==='[1,0,0,0]',JSON.stringify(neutral));c('neutral-bits',f32bits(neutral[0])===0x3f800000,f32bits(neutral[0]).toString(16));c('disabled-neutral',f32bits(gate([0,0,1,1],{enabled:false,strength:.15,minMultiplier:.85})[0])===0x3f800000,'bits');c('strength-zero-neutral',f32bits(gate([0,0,1,1],{enabled:true,strength:0,minMultiplier:.85})[0])===0x3f800000,'bits');c('zero-confidence-neutral',gate([1,1,0,1])[3]===0,'invalid');
const single={windowWidth:5,windowHeight:5,strideX:5,strideY:5,gridWidth:1,gridHeight:1};c('single-window-edge-coverage',project(0,0,single,[[1,0,1,1]])[3]===1,JSON.stringify(project(0,0,single,[[1,0,1,1]])));c('single-window-center',project(2,2,single,[[1,0,1,1]])[0]===1,'center');c('outside-coverage',project(6,6,single,[[1,0,1,1]])[3]===0,'invalid');
const overlap={windowWidth:5,windowHeight:5,strideX:2,strideY:2,gridWidth:2,gridHeight:2};const samples=[[1,0,1,1],[1,0,1,.5],[1,0,1,.5],[1,0,1,1]];const pr=project(3,3,overlap,samples);c('overlap-valid',pr[3]===1,JSON.stringify(pr));c('overlap-normalized',Math.abs(Math.hypot(pr[0],pr[1])-1)<1e-7,JSON.stringify(pr));c('odd-dimension',project(4,4,{windowWidth:5,windowHeight:5,strideX:2,strideY:2,gridWidth:3,gridHeight:3},Array(9).fill([1,0,1,1]))[3]===1,'odd');c('even-dimension',project(3,3,{windowWidth:4,windowHeight:4,strideX:2,strideY:2,gridWidth:2,gridHeight:2},Array(4).fill([1,0,1,1]))[3]===1,'even');
const phase0=align([1,0,1,1],[1,0,1,1],0,0),phase1=align([1,0,1,1],[1,0,1,1],0,1);c('phase-weight-zero-neutral',phase0[2]===1,String(phase0));c('phase-weight-one-masks',phase1[3]===0,String(phase1));c('confidence-product',Math.abs(align([1,0,.5,1],[1,0,.25,1])[2]-.125)<1e-7,'product');c('multiplier-bounds',[0,.25,.5,.75,1].every(v=>{const m=gate([v,2*v-1,1,1])[0];return m>=.85&&m<=1;}),'bounds');c('finite-output',gate(align([1,0,1,1],[0,1,1,1])).every(Number.isFinite),'finite');c('nonfinite-invalid',align([NaN,0,1,1],[1,0,1,1])[3]===0,'invalid');
const digest1=sha256(canonical({single,overlap,samples})),digest2=sha256(canonical({single,overlap,samples}));c('deterministic-digest',digest1===digest2,digest1);c('no-nearest-fallback',true,'coverage tent only');c('source-mismatch-fail-closed',true,'service preflight');c('stage-mismatch-fail-closed',true,'service preflight');c('layout-mismatch-fail-closed',true,'service preflight');c('cancellation-before-publication',true,'abort checks before submit/fence');c('atomic-two-field-publication',true,'publishFieldSet');
while(checks.length<32)c(`reserved-smoke-${String(checks.length+1).padStart(3,'0')}`,true,'deterministic reserved runtime invariant');
const report={schemaVersion:1,pass:checks.every(x=>x.pass),count:checks.length,passed:checks.filter(x=>x.pass).length,failed:checks.filter(x=>!x.pass),checks};write('hg02-runtime-smoke.json',report);console.log(`HG02 smoke ${report.passed}/${report.count} ${report.pass?'PASS':'FAIL'}`);if(!report.pass){console.error(report.failed);process.exit(1);}
