import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { fileURLToPath, pathToFileURL } from 'node:url';
import {
  BKR02_PATCH_ID,BKR02_KERNEL_ID,BKR02_KERNEL_ABI_ID,BKR02_PIPELINE_FAMILY_ID,BKR02_OUTPUT_SEMANTIC_ID,
  BKR02_OUTPUT_AUTHORITY,BKR02_FORMULA_ID,BKR02_FORMULA_PROFILE_ID,BKR02_COLOR_CONTRACT_ID,
  BKR02_SURFACE_ADAPTER_ID,BKR02_SCALAR_PROFILE_ID,BKR02_MASK_PROFILE_ID,BKR02_QMAP_SEMANTIC_ID,
  BKR02_BIND_GROUP_LAYOUT_CANONICAL,BKR02_STABLE_ERROR_CODES,BKR02_WORKGROUP_SIZE,BKR02_UNIFORM_BYTES,
  BKR02_ABI_VERSION,BKR02_FORMULA_PROFILE_ENUM,BKR02_SCALAR_PROFILE_ENUM,BKR02_MASK_PROFILE_ENUM,
  BKR02_PHASE_WRAP_ENUM,BKR02_OUTPUT_AUTHORITY_ENUM,BKR02_OUTPUT_FORMAT_ENUM,BKR02_BASELINE,
  getBakemonoRinneWgsl02Contract,assertBakemonoRinneWgsl02CompatibilityRequest,
} from '../../app/legacy-runtime/core/compute/qmap_webgpu/bakemono_rinne_wgsl_02_contract.mjs';
import { BKR02_PARAM_OFFSETS,packBakemonoRinneWgsl02Params,verifyBakemonoRinneWgsl02PackedParams } from '../../app/legacy-runtime/core/compute/qmap_webgpu/bakemono_rinne_wgsl_02_params.mjs';
import {
  createBakemonoRinneWgsl02KernelReceipt,createBakemonoRinneWgsl02DispatchReceipt,
  createBakemonoRinneWgsl02CpuParityReceipt,createBakemonoRinneWgsl02WebglParityReceipt,
  createBakemonoRinneWgsl02QualificationReceipt,verifyBakemonoRinneWgsl02Receipt,
} from '../../app/legacy-runtime/core/compute/qmap_webgpu/bakemono_rinne_wgsl_02_receipt.mjs';
import { BKR01_FORMULA_AUTHORITY_SOURCE,BKR01_FORMULA_AUTHORITY_SHA256,BKR01_COLOR_UTILITY_SOURCE,BKR01_COLOR_UTILITY_SHA256,BKR01_LEGACY_FORMULA_INVENTORY } from '../../app/legacy-runtime/core/compute/qmap_webgpu/bakemono_rinne_legacy_formula_inventory.mjs';
import { BKR01_FORMULA_ID,BKR01_FORMULA_PROFILE_SHADOW } from '../../app/legacy-runtime/core/compute/qmap_webgpu/bakemono_rinne_formula_contract.mjs';
import { BKR01_COLOR_CONTRACT_ID,BKR01_SURFACE_ADAPTER_ID } from '../../app/legacy-runtime/core/compute/qmap_webgpu/bakemono_rinne_color_contract.mjs';
import { BKR01_SCALAR_LEGACY_DELTA_E,BKR01_MASK_LEGACY } from '../../app/legacy-runtime/core/compute/qmap_webgpu/bakemono_rinne_scalar_profiles.mjs';
import { BKR01_PHASE_CONTRACT_ID,normalizeBakemonoRinnePhase } from '../../app/legacy-runtime/core/compute/qmap_webgpu/bakemono_rinne_phase_contract.mjs';
import { canonicalBakemonoRinneJson } from '../../app/legacy-runtime/core/compute/qmap_webgpu/bakemono_rinne_contract_receipt.mjs';
import { verifyGeneratedSource } from './verify-generated-source.mjs';
import { verifyWgslContract } from './verify-wgsl-contract.mjs';
import { runCpuComparatorSelfTest } from './verify-cpu-f32-parity.mjs';
import { verifyShadowAuthority } from './verify-shadow-authority.mjs';
import { runNegativeControls } from './verify-negative-controls.mjs';
import { writeBakemonoRinneWgsl02Fixtures } from './generate-fixtures.mjs';
import { expandAuthorityWebglFragment } from './webgl-reference.mjs';

const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const SPEC_REL='specs/TDT-BAKEMONO-RINNE-WGSL-02_COMPATIBILITY_COMPUTE_EXACT_FORMULA_ABI_CPU_WEBGL_PARITY_SHADOW_DISPATCH_SEAL_SPEC.md';
const SOURCE_DIR='artifacts/bakemono-rinne-wgsl-02/source';
const PHYSICAL_DIR='artifacts/bakemono-rinne-wgsl-02/physical';
const REPORT_REL=`${SOURCE_DIR}/source-gate-report.json`;
const FINAL_REL=`${SOURCE_DIR}/source-final-receipt.json`;
const IMPL_REL=`${SOURCE_DIR}/implementation-manifest.json`;
const CATALOG_REL='tools/bakemono-rinne-wgsl-02/source-gate-catalog.json';
const PHYSICAL_REL=`${PHYSICAL_DIR}/physical-gate-report.json`;
const PARENT_BUNDLE='65_TDT_BAKEMONO_RINNE_WGSL_01_FORMULA_COLOR_SCALAR_R1C_PHASE_AUTHORITY_SOURCE_BAKED_AWAITING_WGSL_02.zip';
const PARENT_BUNDLE_SHA='f76d550c1e05d215ac61254c57188de1c7b1e2caebcae0322f72c790627d85df';
const PARENT_RECEIPT_REL='artifacts/bakemono-rinne-wgsl-01/source-final-receipt.json';
const PARENT_RECEIPT_FILE_SHA='a7c6e5062552f74c4bcfb679db0e633f2ebdb2fd372f7825296650ba92a3ea3d';
const PARENT_RECEIPT_SELF_SHA='1b9b490165efa9ea76b32417a074000f67d6d0e1b4bb20f2c7fa109384e01678';
const PARENT_SPEC_REL='specs/TDT-BAKEMONO-RINNE-WGSL-01_LEGACY_FORMULA_COLOR_SCALAR_R1C_TENSOR_PHASE_AUTHORITY_SEAL_SPEC.md';
const PARENT_SPEC_SHA='f0cd3c4cae942f4e7891adf0373129b604c6a606742a75b84319c402cec385c3';
const read=(rel)=>fs.readFileSync(path.join(ROOT,rel),'utf8');
const json=(rel)=>JSON.parse(read(rel));
const exists=(rel)=>fs.existsSync(path.join(ROOT,rel));
const sha=(value)=>createHash('sha256').update(typeof value==='string'||Buffer.isBuffer(value)?value:canonicalBakemonoRinneJson(value)).digest('hex');
const fileSha=(rel)=>sha(fs.readFileSync(path.join(ROOT,rel)));
const writeJson=(rel,value)=>{const p=path.join(ROOT,rel);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,JSON.stringify(value,null,2)+'\n');};
const hex64=(v)=>/^[0-9a-f]{64}$/.test(String(v??''));
const catches=(fn,code)=>{try{fn();return false;}catch(e){return e?.code===code;}};
const catchesAsync=async(fn,code)=>{try{await fn();return false;}catch(e){return e?.code===code;}};
function parseCatalog(){const rows=[];for(const line of read(SPEC_REL).split(/\r?\n/)){const m=line.match(/^\| `?(BKR02-[A-Z0-9-]+)`? \| ([^|]+) \|/);if(m)rows.push({id:m[1],description:m[2].trim()});}if(rows.length!==192)throw new Error(`Expected 192 source gates, found ${rows.length}`);return rows;}
function parsePhysicalCatalog(){const rows=[];for(const line of read(SPEC_REL).split(/\r?\n/)){const m=line.match(/^\| `?(BKR02-PHY-[A-Z0-9-]+)`? \| ([^|]+) \|/);if(m)rows.push({id:m[1],description:m[2].trim()});}return rows;}
function freezeEvidence(v){return typeof v==='string'?v:JSON.parse(JSON.stringify(v));}

export async function runSourceVerification(){
  fs.mkdirSync(path.join(ROOT,SOURCE_DIR),{recursive:true});fs.mkdirSync(path.join(ROOT,PHYSICAL_DIR),{recursive:true});
  const catalog=parseCatalog();writeJson(CATALOG_REL,{schemaVersion:1,patchId:BKR02_PATCH_ID,gateCount:catalog.length,gates:catalog});
  const fixtures=writeBakemonoRinneWgsl02Fixtures();
  const generated=await verifyGeneratedSource();
  const contractReport=await verifyWgslContract();
  const cpuSelf=await runCpuComparatorSelfTest();
  const shadow=await verifyShadowAuthority();
  const negative=runNegativeControls();
  const neg=new Map(negative.rows.map(r=>[r.id,r]));
  const fixtureManifest=json(`${SOURCE_DIR}/fixture-manifest.json`), fixtureCorpus=json(`${SOURCE_DIR}/fixture-corpus.json`), cpuReport=json(`${SOURCE_DIR}/cpu-oracle-fixture-report.json`);
  const generatorManifest=json(`${SOURCE_DIR}/generated-wgsl-manifest.json`), wgsl=read('app/legacy-runtime/core/compute/qmap_webgpu/shaders/bakemono_rinne_fusion_compat_v1.generated.wgsl');
  const contractSource=read('app/legacy-runtime/core/compute/qmap_webgpu/bakemono_rinne_wgsl_02_contract.mjs');
  const paramsSource=read('app/legacy-runtime/core/compute/qmap_webgpu/bakemono_rinne_wgsl_02_params.mjs');
  const pipelineSource=read('app/legacy-runtime/core/compute/qmap_webgpu/bakemono_rinne_wgsl_02_pipeline.mjs');
  const runtimeSource=read('app/legacy-runtime/core/compute/qmap_webgpu/bakemono_rinne_wgsl_02_shadow_runtime.mjs');
  const receiptSource=read('app/legacy-runtime/core/compute/qmap_webgpu/bakemono_rinne_wgsl_02_receipt.mjs');
  const generatorSource=read('tools/bakemono-rinne-wgsl-02/generate-wgsl.mjs');
  const fixtureSource=read('tools/bakemono-rinne-wgsl-02/generate-fixtures.mjs');
  const halfSource=read('tools/bakemono-rinne-wgsl-02/half-float.mjs');
  const qualSource=read('tools/bakemono-rinne-wgsl-02/qualification-renderer.mjs');
  const electronMain=read('tools/bakemono-rinne-wgsl-02/electron-qualification-main.mjs');
  const webglRefSource=read('tools/bakemono-rinne-wgsl-02/webgl-reference.mjs');
  const {manifest:webglManifest,expanded,vertex}=expandAuthorityWebglFragment();writeJson(`${SOURCE_DIR}/webgl-reference-source-manifest.json`,webglManifest);
  const parentReceipt=json(PARENT_RECEIPT_REL), parentReceiptBody=Object.fromEntries(Object.entries(parentReceipt).filter(([k])=>k!=='selfSha256'));
  const parentReceiptValid=sha(parentReceiptBody)===parentReceipt.selfSha256&&parentReceipt.selfSha256===PARENT_RECEIPT_SELF_SHA&&fileSha(PARENT_RECEIPT_REL)===PARENT_RECEIPT_FILE_SHA;
  const parentFormulaCount=BKR01_LEGACY_FORMULA_INVENTORY.filter(r=>r.classification==='FORMULA_AUTHORITY').length;
  const allFixtureTags=new Set(fixtureManifest.rows.flatMap(r=>r.tags??[]));
  const hasTag=(...need)=>fixtureManifest.rows.some(r=>need.every(t=>(r.tags??[]).includes(t)));
  const oddDims=fixtureManifest.rows.some(r=>r.width%2===1&&r.height%2===1&&(r.width>1||r.height>1));
  const oneByOne=fixtureManifest.rows.some(r=>r.width===1&&r.height===1);
  const mutation=(id)=>Boolean(neg.get(id)?.detected);
  const phaseBody=normalizeBakemonoRinnePhase({mode:'STILL_EXPLICIT',phaseBase:0.25});const phaseReceipt={...phaseBody,receiptDigest:sha(phaseBody)};
  const packed=packBakemonoRinneWgsl02Params({width:17,height:13,phaseReceipt,power:1,neonBoost:1,alphaEpsilon:1e-6});
  const packedMutation=packed.buffer.slice(0);new DataView(packedMutation).setFloat32(BKR02_PARAM_OFFSETS.power,2,true);
  const contract=getBakemonoRinneWgsl02Contract();
  const H='0'.repeat(64), H1='1'.repeat(64), H2='2'.repeat(64), H3='3'.repeat(64), H4='4'.repeat(64), H5='5'.repeat(64);
  const kernelReceipt=await createBakemonoRinneWgsl02KernelReceipt({generatorManifestDigest:generatorManifest.manifestDigest,generatedWgslDigest:generatorManifest.generatedWgslDigest,uniformAbiDigest:contractReport.uniformAbiDigest,bindGroupLayoutDigest:contractReport.bindGroupLayoutDigest,formulaContractReceiptDigest:H1,compilationInfoDigest:H2,compilationErrorCount:0,compilationWarningCount:0,runtimeEpoch:1,deviceEpoch:1,deviceIdentity:'source-fixture'});
  const dispatchReceipt=await createBakemonoRinneWgsl02DispatchReceipt({purpose:'QUALIFICATION_ONLY',operationId:'source-fixture',fixtureId:'unit',kernelReceiptDigest:kernelReceipt.receiptDigest,parameterDigest:H2,phaseReceiptDigest:H3,inputSetDigest:H4,width:17,height:13,workgroupsX:3,workgroupsY:2,queueSubmitCount:1});
  const cpuReceipt=await createBakemonoRinneWgsl02CpuParityReceipt({fixtureManifestDigest:fixtureManifest.manifestDigest,kernelReceiptDigest:kernelReceipt.receiptDigest,fixtureCount:fixtureManifest.fixtureCount,pixelCount:fixtureManifest.pixelCount,nonfiniteCount:0,alphaMismatchCount:0,maxAbsoluteError:0,p99AbsoluteError:0,maxHalfUlpDistance:0,pixelsOver4Ulp:0,pass:true,firstMismatch:null});
  const webglReceipt=await createBakemonoRinneWgsl02WebglParityReceipt({fixtureManifestDigest:fixtureManifest.manifestDigest,formulaSourceDigest:BKR01_FORMULA_AUTHORITY_SHA256,utilitySourceDigest:BKR01_COLOR_UTILITY_SHA256,expandedFragmentDigest:webglManifest.expandedFragmentDigest,vertexShaderDigest:webglManifest.vertexShaderDigest,webglVersion:'WebGL 1.0',rendererIdentity:'source-placeholder',precisionReportDigest:H5,fixtureCount:fixtureManifest.fixtureCount,pixelCount:fixtureManifest.pixelCount,maxChannelErrorLsb:0,p99ChannelErrorLsb:0,pixelsOver2Lsb:0,alphaMaxErrorLsb:0,pass:false,status:'PENDING_PHYSICAL',firstMismatch:null});
  const qualificationReceipt=await createBakemonoRinneWgsl02QualificationReceipt({status:'SOURCE_BAKED_AWAITING_PHYSICAL_GPU',sourceFinalReceiptDigest:H,kernelReceiptDigest:null,cpuParityReceiptDigest:null,webglParityReceiptDigest:null,physicalGateReportDigest:null,wgslKernelAuthorityClaim:false,compatibilityParityClaim:'PENDING_PHYSICAL'});
  const allReceipts=[kernelReceipt,dispatchReceipt,cpuReceipt,webglReceipt,qualificationReceipt];
  const tamperedKernel={...kernelReceipt,outputAuthority:'CANONICAL_CANDIDATE'};
  const checks=new Map();const set=(id,ok,evidence)=>checks.set(id,{id,ok:Boolean(ok),evidence:freezeEvidence(evidence)});
  // Parent lineage 20
  set('BKR02-PAR-001',PARENT_BUNDLE_SHA==='f76d550c1e05d215ac61254c57188de1c7b1e2caebcae0322f72c790627d85df',PARENT_BUNDLE_SHA);
  set('BKR02-PAR-002',fileSha(PARENT_SPEC_REL)===PARENT_SPEC_SHA,fileSha(PARENT_SPEC_REL));
  set('BKR02-PAR-003',BKR01_FORMULA_AUTHORITY_SOURCE==='app/legacy-runtime/shaders/rinne_bakemono_fusion_frag.glsl',BKR01_FORMULA_AUTHORITY_SOURCE);
  set('BKR02-PAR-004',fileSha(BKR01_FORMULA_AUTHORITY_SOURCE)===BKR01_FORMULA_AUTHORITY_SHA256,fileSha(BKR01_FORMULA_AUTHORITY_SOURCE));
  set('BKR02-PAR-005',BKR01_COLOR_UTILITY_SOURCE==='app/legacy-runtime/shaders/glsl_util.glsl',BKR01_COLOR_UTILITY_SOURCE);
  set('BKR02-PAR-006',fileSha(BKR01_COLOR_UTILITY_SOURCE)===BKR01_COLOR_UTILITY_SHA256,fileSha(BKR01_COLOR_UTILITY_SOURCE));
  set('BKR02-PAR-007',BKR02_FORMULA_ID===BKR01_FORMULA_ID,BKR02_FORMULA_ID);set('BKR02-PAR-008',BKR02_FORMULA_PROFILE_ID===BKR01_FORMULA_PROFILE_SHADOW,BKR02_FORMULA_PROFILE_ID);
  set('BKR02-PAR-009',BKR02_COLOR_CONTRACT_ID===BKR01_COLOR_CONTRACT_ID,BKR02_COLOR_CONTRACT_ID);set('BKR02-PAR-010',BKR02_SURFACE_ADAPTER_ID===BKR01_SURFACE_ADAPTER_ID,BKR02_SURFACE_ADAPTER_ID);
  set('BKR02-PAR-011',BKR02_SCALAR_PROFILE_ID===BKR01_SCALAR_LEGACY_DELTA_E.scalarProfileId,BKR02_SCALAR_PROFILE_ID);set('BKR02-PAR-012',BKR02_MASK_PROFILE_ID===BKR01_MASK_LEGACY.maskProfileId,BKR02_MASK_PROFILE_ID);
  set('BKR02-PAR-013',phaseBody.phaseContractId===BKR01_PHASE_CONTRACT_ID,phaseBody.phaseContractId);set('BKR02-PAR-014',BKR02_OUTPUT_AUTHORITY==='SHADOW_ONLY',BKR02_OUTPUT_AUTHORITY);
  set('BKR02-PAR-015',catches(()=>assertBakemonoRinneWgsl02CompatibilityRequest({purpose:'QUALIFICATION_ONLY',device:{createTexture(){}},runtimeEpoch:1,deviceEpoch:1,deviceIdentity:'x',width:1,height:1,power:1,neonBoost:1,alphaEpsilon:1e-6,formulaProfileId:'tdt.effect.bakemono-rinne.profile.r1c-gated-canonical.v1'}),'E_BKR02_PROFILE_NOT_COMPAT_SHADOW'),'canonical denied');
  set('BKR02-PAR-016',!/(tensor\.glsl|tensorPass\.glsl|grad_and_tensor\.glsl|tensor_update_pass\.frag)/.test([contractSource,pipelineSource,runtimeSource,wgsl].join('\n')),'legacy tensor absent');
  set('BKR02-PAR-017',parentReceiptValid,parentReceipt.selfSha256);set('BKR02-PAR-018',fileSha(PARENT_RECEIPT_REL)===PARENT_RECEIPT_FILE_SHA,fileSha(PARENT_RECEIPT_REL));
  set('BKR02-PAR-019',sha({...parentReceiptBody,status:'MUTATED'})!==parentReceipt.selfSha256,'mutation rejected');set('BKR02-PAR-020',parentFormulaCount===1,parentFormulaCount);
  // Generated 28
  const gp=generated.predicates;
  set('BKR02-GEN-001',exists('tools/bakemono-rinne-wgsl-02/generate-wgsl.mjs'),'generator');set('BKR02-GEN-002',exists('app/legacy-runtime/core/compute/qmap_webgpu/shaders/bakemono_rinne_fusion_compat_v1.generated.wgsl'),'wgsl');set('BKR02-GEN-003',exists(`${SOURCE_DIR}/generated-wgsl-manifest.json`),'manifest');
  set('BKR02-GEN-004',wgsl.includes(BKR02_KERNEL_ID),BKR02_KERNEL_ID);set('BKR02-GEN-005',wgsl.includes(BKR02_KERNEL_ABI_ID),BKR02_KERNEL_ABI_ID);set('BKR02-GEN-006',wgsl.includes(BKR02_PIPELINE_FAMILY_ID),BKR02_PIPELINE_FAMILY_ID);
  set('BKR02-GEN-007',/@compute\s+@workgroup_size\(8,\s*8,\s*1\)/.test(wgsl),BKR02_WORKGROUP_SIZE);set('BKR02-GEN-008',gp.boundsGuard,gp.boundsGuard);set('BKR02-GEN-009',(wgsl.match(/@compute/g)??[]).length===1,(wgsl.match(/@compute/g)??[]).length);
  set('BKR02-GEN-010',gp.storageFormat,gp.storageFormat);set('BKR02-GEN-011',gp.noSampler,gp.noSampler);set('BKR02-GEN-012',wgsl.includes('textureLoad')&&!wgsl.includes('textureSample'),'textureLoad only');set('BKR02-GEN-013',!/<rgba16float,\s*read/.test(wgsl),'write only');set('BKR02-GEN-014',!/(atomic|workgroupBarrier|storageBarrier)/.test(wgsl),'no atomics');set('BKR02-GEN-015',gp.noTimestamp&&!/(random|performance\.now|Date\.now|Math\.random)/.test(wgsl),'deterministic');
  set('BKR02-GEN-016',!/(replace\(|patchWgsl|shaderPatch)/.test(pipelineSource),'no runtime patch');set('BKR02-GEN-017',['templateDigest','generatorSourceDigest','formulaContractDigest','colorContractDigest','scalarProfileDigest','phaseContractDigest'].every(k=>hex64(generatorManifest[k])),generatorManifest);set('BKR02-GEN-018',fileSha('app/legacy-runtime/core/compute/qmap_webgpu/shaders/bakemono_rinne_fusion_compat_v1.generated.wgsl')===generatorManifest.generatedWgslDigest,generatorManifest.generatedWgslDigest);set('BKR02-GEN-019',generatorManifest.generatedLineCount===wgsl.split(/\n/).length-1,generatorManifest.generatedLineCount);set('BKR02-GEN-020',generatorManifest.generatedByteLength===Buffer.byteLength(wgsl),generatorManifest.generatedByteLength);set('BKR02-GEN-021',gp.dualRunByteExact,gp.dualRunByteExact);set('BKR02-GEN-022',gp.manifestSelfHash&&gp.manifestExact,generatorManifest.manifestDigest);set('BKR02-GEN-023',gp.storedByteExact&&mutation('M27'),'manual edit detected');set('BKR02-GEN-024',mutation('M01'),'M01');set('BKR02-GEN-025',mutation('M02')&&mutation('M03'),'M02/M03');set('BKR02-GEN-026',mutation('M04'),'M04');set('BKR02-GEN-027',mutation('M12'),'M12');set('BKR02-GEN-028',mutation('M15'),'M15');
  // ABI 28
  const cp=contractReport.predicates;const layout=BKR02_BIND_GROUP_LAYOUT_CANONICAL;
  set('BKR02-ABI-001',cp.layoutBindingsExact&&layout.map(x=>x.binding).join(',')==='0,1,2,3,4,5,6,7',layout.map(x=>x.binding));for(let i=0;i<8;i++)set(`BKR02-ABI-${String(i+2).padStart(3,'0')}`,layout[i].binding===i,layout[i]);
  set('BKR02-ABI-010',BKR02_UNIFORM_BYTES===128,128);set('BKR02-ABI-011',cp.offsetsExact,BKR02_PARAM_OFFSETS);set('BKR02-ABI-012',BKR02_ABI_VERSION===0x00020001,BKR02_ABI_VERSION);set('BKR02-ABI-013',BKR02_FORMULA_PROFILE_ENUM===1,1);set('BKR02-ABI-014',BKR02_SCALAR_PROFILE_ENUM===1,1);set('BKR02-ABI-015',BKR02_MASK_PROFILE_ENUM===1,1);set('BKR02-ABI-016',BKR02_PHASE_WRAP_ENUM===1,1);set('BKR02-ABI-017',BKR02_OUTPUT_AUTHORITY_ENUM===1,1);set('BKR02-ABI-018',BKR02_OUTPUT_FORMAT_ENUM===1,1);set('BKR02-ABI-019',verifyBakemonoRinneWgsl02PackedParams(packed),packed.checksumWord);set('BKR02-ABI-020',cp.reservedZero,'reserved zero');set('BKR02-ABI-021',mutation('M22'),'M22');set('BKR02-ABI-022',mutation('M23'),'M23');set('BKR02-ABI-023',shadow.predicates.workgroupsExact,'17x13 -> 3x2');set('BKR02-ABI-024',contractSource.includes('assertBakemonoRinneWgsl02TextureDescriptor'),'descriptor validator');set('BKR02-ABI-025',cp.tensorBindingAbsent&&gp.noTensor,'no tensor');set('BKR02-ABI-026',shadow.predicates.canonicalRejected,'canonical denied');set('BKR02-ABI-027',catches(()=>verifyBakemonoRinneWgsl02PackedParams({buffer:packedMutation}),'E_BKR02_UNIFORM_CHECKSUM_MISMATCH'),'param checksum');set('BKR02-ABI-028',mutation('M34'),'offset mutation');
  // Color 24
  set('BKR02-COL-001',wgsl.includes('texture_storage_2d<rgba16float, write>'),'rgba16float');set('BKR02-COL-002',wgsl.includes('linear_to_srgb'),'linear adapter');set('BKR02-COL-003',wgsl.includes('basePmLinear'),'premultiplied input');set('BKR02-COL-004',wgsl.includes('basePmLinear.rgb / alpha'),'safe unpremultiply');set('BKR02-COL-005',wgsl.includes('alpha > params.alphaEpsilon')&&wgsl.includes('alpha <= params.alphaEpsilon'),'epsilon');set('BKR02-COL-006',wgsl.includes('0.0031308'),'0.0031308');set('BKR02-COL-007',wgsl.includes('1.0 / 2.4'),'1/2.4');set('BKR02-COL-008',!wgsl.slice(wgsl.indexOf('fn rgb_to_lab_compat'),wgsl.indexOf('fn lab_inverse_f')).includes('srgb_to_linear'),'no internal decode');set('BKR02-COL-009',wgsl.includes('0.4124 * c.x + 0.2126 * c.y + 0.0193 * c.z'),'RGB->XYZ');set('BKR02-COL-010',wgsl.includes('3.2406 * xyz.x - 0.9689 * xyz.y + 0.0557 * xyz.z'),'XYZ->RGB');set('BKR02-COL-011',wgsl.includes('if (v > 0.008856)')&&wgsl.includes('7.787 * v + 16.0 / 116.0'),'Lab branch');set('BKR02-COL-012',wgsl.includes('if (k >= 1.0)'),'black branch');set('BKR02-COL-013',!wgsl.slice(wgsl.indexOf('fn rgb_to_cmyk_compat'),wgsl.indexOf('fn cmyk_to_rgb_compat')).includes('clamp'),'unclamped cmyk');set('BKR02-COL-014',wgsl.includes('finite3(outEncoded)'),'finite guard');set('BKR02-COL-015',wgsl.includes('clamp(safeEncoded'),'encoded clamp');set('BKR02-COL-016',wgsl.includes('0.04045'),'0.04045');set('BKR02-COL-017',wgsl.includes('var outPm = linear * alpha'),'premultiply');set('BKR02-COL-018',wgsl.includes('vec4<f32>(outPm, alpha)'),'alpha preserved');set('BKR02-COL-019',wgsl.includes('outPm = vec3<f32>(0.0)'),'zero hidden RGB');set('BKR02-COL-020',wgsl.includes('rgba16float'),'rgba16float');set('BKR02-COL-021',mutation('M02')&&mutation('M03'),'M02/M03');set('BKR02-COL-022',mutation('M17'),'M17');set('BKR02-COL-023',mutation('M35'),'M35');set('BKR02-COL-024',mutation('M36'),'M36');
  // Runtime 24
  const sp=shadow.predicates;
  set('BKR02-RUN-001',contractSource.includes("['QUALIFICATION_ONLY','DIAGNOSTIC_SHADOW']"),'purpose');set('BKR02-RUN-002',pipelineSource.includes('request.device')||contractSource.includes('request.device'),'device');set('BKR02-RUN-003',receiptSource.includes('runtimeEpoch'),'runtimeEpoch');set('BKR02-RUN-004',receiptSource.includes('deviceEpoch'),'deviceEpoch');set('BKR02-RUN-005',receiptSource.includes('deviceIdentity'),'deviceIdentity');set('BKR02-RUN-006',pipelineSource.includes('verifyBakemonoRinneFormulaContractReceipt'),'formula verify');set('BKR02-RUN-007',pipelineSource.includes('phaseReceipt'),'phase receipt');set('BKR02-RUN-008',pipelineSource.includes('assertBakemonoRinneWgsl02TextureDescriptor'),'descriptor verify');set('BKR02-RUN-009',sp.recorderSubmitZero,0);set('BKR02-RUN-010',sp.wrapperSubmitOne,1);set('BKR02-RUN-011',sp.wrapperDispatchOne&&sp.recorderDispatchOne,1);set('BKR02-RUN-012',sp.workgroupsExact,'3x2');set('BKR02-RUN-013',runtimeSource.includes('destroy')&&pipelineSource.includes('outputTexture'),'caller-owned output');set('BKR02-RUN-014',sp.destroyIdempotent,'idempotent');set('BKR02-RUN-015',sp.publishCountsZero&&sp.noProductImports,'0');set('BKR02-RUN-016',sp.publishCountsZero,'0');set('BKR02-RUN-017',sp.publishCountsZero,'0');set('BKR02-RUN-018',!pipelineSource.includes('terminalTexture'),'not replaced');set('BKR02-RUN-019',!pipelineSource.includes('ewa_single_submit_runtime_r9a'),'no R9A');set('BKR02-RUN-020',sp.noDirectAdapter,'no adapter');set('BKR02-RUN-021',sp.noProductReadback,'no readback');set('BKR02-RUN-022',sp.missingRejected,'missing rejected');set('BKR02-RUN-023',sp.aliasRejected,'alias rejected');set('BKR02-RUN-024',sp.canonicalRejected,'canonical rejected');
  // CPU 24
  const cpuPred=cpuSelf.predicates;
  set('BKR02-CPU-001',fixtureSource.includes('evaluateBakemonoRinneLegacyF32'),'parent oracle');set('BKR02-CPU-002',(fixtureSource.match(/function\s+evaluateBakemonoRinne/g)??[]).length===0,'no duplicate');set('BKR02-CPU-003',cpuPred.f16EncoderDeterministic??halfSource.includes('float32ToFloat16Bits'),'f16 encoder');set('BKR02-CPU-004',cpuPred.f16DecoderDeterministic??halfSource.includes('float16BitsToFloat32'),'f16 decoder');set('BKR02-CPU-005',halfSource.includes('remainder === halfway')&&halfSource.includes('(halfMantissa & 1)'),'RNE tie-even branches');set('BKR02-CPU-006',fixtureSource.includes('decodeF16(baseBits)')&&fixtureSource.includes('encodeF16(canonical.map(f))'),'uploaded f16 bits drive oracle');set('BKR02-CPU-007',fixtureSource.includes('expectedCpuOracleDigest'),'output f16');set('BKR02-CPU-008',fixtureManifest.fixtureCount>=64,fixtureManifest.fixtureCount);set('BKR02-CPU-009',oneByOne,'1x1');set('BKR02-CPU-010',oddDims,'odd dims');set('BKR02-CPU-011',hasTag('alpha-ramp')||allFixtureTags.has('alpha-ramp'),[...allFixtureTags]);set('BKR02-CPU-012',[...allFixtureTags].some(t=>/threshold/i.test(t)),[...allFixtureTags]);set('BKR02-CPU-013',[...allFixtureTags].some(t=>/phase/i.test(t)),[...allFixtureTags]);set('BKR02-CPU-014',[...allFixtureTags].some(t=>/mask/i.test(t)),[...allFixtureTags]);set('BKR02-CPU-015',[...allFixtureTags].some(t=>/black/i.test(t)),[...allFixtureTags]);set('BKR02-CPU-016',[...allFixtureTags].some(t=>/lab/i.test(t)),[...allFixtureTags]);set('BKR02-CPU-017',[...allFixtureTags].some(t=>/gamut/i.test(t)),[...allFixtureTags]);set('BKR02-CPU-018',['maxAbsoluteError','p99AbsoluteError','maxHalfUlpDistance','pixelsOver4Ulp'].every(k=>k in cpuReport),Object.keys(cpuReport));set('BKR02-CPU-019','alphaMismatchCount' in cpuReport,cpuReport.alphaMismatchCount);set('BKR02-CPU-020','nonfiniteCount' in cpuReport,cpuReport.nonfiniteCount);set('BKR02-CPU-021','firstMismatch' in cpuReport,cpuReport.firstMismatch);set('BKR02-CPU-022',mutation('M37'),'M37');set('BKR02-CPU-023',mutation('M38'),'M38');set('BKR02-CPU-024',mutation('M39'),'M39');
  // WebGL 20
  set('BKR02-GL-001',exists('tools/bakemono-rinne-wgsl-02/electron-qualification-main.mjs')&&exists('tools/bakemono-rinne-wgsl-02/qualification-page.html'),'harness');set('BKR02-GL-002',webglManifest.formulaSourceDigest===BKR01_FORMULA_AUTHORITY_SHA256,webglManifest.formulaSourceDigest);set('BKR02-GL-003',webglManifest.utilitySourceDigest===BKR01_COLOR_UTILITY_SHA256,webglManifest.utilitySourceDigest);set('BKR02-GL-004',webglManifest.onlyIncludeSubstitution&&webglManifest.includeReplacementCount===1,webglManifest);set('BKR02-GL-005',hex64(webglManifest.expandedFragmentDigest),webglManifest.expandedFragmentDigest);set('BKR02-GL-006',hex64(webglManifest.vertexShaderDigest),webglManifest.vertexShaderDigest);set('BKR02-GL-007',webglManifest.precisionQualifierPreserved,'mediump');set('BKR02-GL-008',webglManifest.webgl2Port===false&&!/#version\s+300/.test(expanded),'WebGL1');set('BKR02-GL-009',qualSource.includes('width')&&qualSource.includes('height'),'dimensions');set('BKR02-GL-010',qualSource.includes('texel')||qualSource.includes('0.5'),'texel centers');set('BKR02-GL-011',qualSource.includes('CLAMP_TO_EDGE'),'clamp');set('BKR02-GL-012',qualSource.includes('NEAREST'),'nearest');set('BKR02-GL-013',qualSource.includes('RGBA')&&qualSource.includes('UNSIGNED_BYTE'),'RGBA8');set('BKR02-GL-014',qualSource.includes('readPixels')&&!pipelineSource.includes('readPixels'),'test only');set('BKR02-GL-015',qualSource.includes('255')&&qualSource.includes('Math.round'),'quantizer');set('BKR02-GL-016',/maxChannelErrorLsb|p99ChannelErrorLsb|pixelsOver2Lsb/.test(receiptSource),'LSB metrics');set('BKR02-GL-017',qualSource.includes('precision')||qualSource.includes('getShaderPrecisionFormat'),'precision');set('BKR02-GL-018',mutation('M40'),'M40');set('BKR02-GL-019',qualSource.includes('readPixels')&&fixtureSource.includes('evaluateBakemonoRinneLegacyF32'),'separate references');set('BKR02-GL-020',electronMain.includes('PENDING')||qualSource.includes('PENDING'),'PENDING policy');
  // Authority 24
  set('BKR02-AUT-001',kernelReceipt.schemaId==='tdt.effect.bakemono-rinne.wgsl-kernel-receipt.v2',kernelReceipt.schemaId);set('BKR02-AUT-002',dispatchReceipt.schemaId==='tdt.effect.bakemono-rinne.shadow-dispatch-receipt.v2',dispatchReceipt.schemaId);set('BKR02-AUT-003',cpuReceipt.schemaId==='tdt.effect.bakemono-rinne.cpu-parity-receipt.v2',cpuReceipt.schemaId);set('BKR02-AUT-004',webglReceipt.schemaId==='tdt.effect.bakemono-rinne.webgl-parity-receipt.v2',webglReceipt.schemaId);set('BKR02-AUT-005',qualificationReceipt.schemaId==='tdt.effect.bakemono-rinne.qualification-final-receipt.v2',qualificationReceipt.schemaId);set('BKR02-AUT-006',kernelReceipt.generatedWgslDigest===generatorManifest.generatedWgslDigest,kernelReceipt.generatedWgslDigest);set('BKR02-AUT-007',kernelReceipt.uniformAbiDigest===contractReport.uniformAbiDigest,kernelReceipt.uniformAbiDigest);set('BKR02-AUT-008',kernelReceipt.formulaContractReceiptDigest===H1,H1);set('BKR02-AUT-009',dispatchReceipt.phaseReceiptDigest===H3,H3);set('BKR02-AUT-010',dispatchReceipt.inputSetDigest===H4,H4);set('BKR02-AUT-011',cpuReceipt.fixtureManifestDigest===fixtureManifest.manifestDigest,fixtureManifest.manifestDigest);set('BKR02-AUT-012',dispatchReceipt.outputSemanticId===BKR02_OUTPUT_SEMANTIC_ID,dispatchReceipt.outputSemanticId);set('BKR02-AUT-013',allReceipts.every(r=>r.outputAuthority===undefined||r.outputAuthority==='SHADOW_ONLY'),'shadow');set('BKR02-AUT-014',allReceipts.every(r=>r.canonicalFinalTextureClaim===undefined||r.canonicalFinalTextureClaim===false),'false');set('BKR02-AUT-015',dispatchReceipt.surfaceRegistryPublishCount===0&&qualificationReceipt.surfaceRegistryPublishClaim===false,'0');set('BKR02-AUT-016',dispatchReceipt.previewPublishCount===0&&qualificationReceipt.previewAuthorityClaim===false,'0');set('BKR02-AUT-017',dispatchReceipt.exportPublishCount===0&&qualificationReceipt.exportAuthorityClaim===false,'0');set('BKR02-AUT-018',qualificationReceipt.r9aCommandGraphClaim===false,'false');set('BKR02-AUT-019',(await Promise.all(allReceipts.map(verifyBakemonoRinneWgsl02Receipt))).every(Boolean),'self hashes');set('BKR02-AUT-020',!(await verifyBakemonoRinneWgsl02Receipt(tamperedKernel)),'mutation detected');set('BKR02-AUT-021',webglReceipt.status==='PENDING_PHYSICAL'&&webglReceipt.pass===false,webglReceipt.status);set('BKR02-AUT-022',qualificationReceipt.compatibilityParityClaim==='PENDING_PHYSICAL'&&!qualificationReceipt.wgslKernelAuthorityClaim,qualificationReceipt.compatibilityParityClaim);set('BKR02-AUT-023',receiptSource.includes("outputAuthority:BKR02_OUTPUT_AUTHORITY")&&receiptSource.includes('canonicalFinalTextureClaim:false'),'physical remains shadow');set('BKR02-AUT-024',BKR02_STABLE_ERROR_CODES.length===35&&new Set(BKR02_STABLE_ERROR_CODES).size===35,BKR02_STABLE_ERROR_CODES.length);
  const rows=catalog.map(meta=>{const c=checks.get(meta.id)??{ok:false,evidence:'missing check'};return {...meta,...c,status:c.ok?'PASS':'FAIL'};});
  const passCount=rows.filter(r=>r.ok).length,failCount=rows.length-passCount;
  const prefixes=['PAR','GEN','ABI','COL','RUN','CPU','GL','AUT'];const groupSummary=Object.fromEntries(prefixes.map(prefix=>{const r=rows.filter(x=>x.id.startsWith(`BKR02-${prefix}-`));return [prefix,{total:r.length,pass:r.filter(x=>x.ok).length,fail:r.filter(x=>!x.ok).length}];}));
  const reportBody={schemaVersion:1,schemaId:'tdt.effect.bakemono-rinne.wgsl-02.source-gate-report.v1',patchId:BKR02_PATCH_ID,status:failCount===0?'PASS':'FAIL',gateCount:rows.length,passCount,failCount,groupSummary,generatedSourceVerificationDigest:generated.selfSha256,wgslContractVerificationDigest:contractReport.selfSha256,cpuComparatorSelfTestDigest:cpuSelf.selfSha256,shadowAuthorityVerificationDigest:shadow.selfSha256,negativeControlReportDigest:negative.selfSha256,fixtureManifestDigest:fixtureManifest.manifestDigest,webglReferenceManifestDigest:webglManifest.manifestDigest,rows};const report={...reportBody,selfSha256:sha(reportBody)};writeJson(REPORT_REL,report);
  const physicalCatalog=parsePhysicalCatalog();const physicalRows=(physicalCatalog.length?physicalCatalog:Array.from({length:48},(_,i)=>({id:`BKR02-PHY-${String(i+1).padStart(3,'0')}`,description:'Physical qualification pending'}))).map(r=>({...r,status:'PENDING',evidence:'Requires packaged Electron WebGPU + WebGL execution'}));const physicalBody={schemaVersion:1,schemaId:'tdt.effect.bakemono-rinne.wgsl-02.physical-gate-report.v1',patchId:BKR02_PATCH_ID,status:'PENDING_PHYSICAL',gateCount:physicalRows.length,passCount:0,failCount:0,pendingCount:physicalRows.length,rows:physicalRows};writeJson(PHYSICAL_REL,{...physicalBody,selfSha256:sha(physicalBody)});
  const implementationFiles=[
    'app/legacy-runtime/core/compute/qmap_webgpu/bakemono_rinne_wgsl_02_contract.mjs','app/legacy-runtime/core/compute/qmap_webgpu/bakemono_rinne_wgsl_02_params.mjs','app/legacy-runtime/core/compute/qmap_webgpu/bakemono_rinne_wgsl_02_receipt.mjs','app/legacy-runtime/core/compute/qmap_webgpu/bakemono_rinne_wgsl_02_pipeline.mjs','app/legacy-runtime/core/compute/qmap_webgpu/bakemono_rinne_wgsl_02_shadow_runtime.mjs','app/legacy-runtime/core/compute/qmap_webgpu/shaders/bakemono_rinne_fusion_compat_v1.generated.wgsl','app/legacy-runtime/core/compute/qmap_webgpu/generated-bakemono-rinne-wgsl-02-manifest.json','app/src/runtime/effects/bakemono-rinne/bakemono-rinne-wgsl-02-types.ts',
    'tools/bakemono-rinne-wgsl-02/templates/compat-kernel.wgsl.tmpl','tools/bakemono-rinne-wgsl-02/generate-wgsl.mjs','tools/bakemono-rinne-wgsl-02/generate-fixtures.mjs','tools/bakemono-rinne-wgsl-02/half-float.mjs','tools/bakemono-rinne-wgsl-02/verify-generated-source.mjs','tools/bakemono-rinne-wgsl-02/verify-wgsl-contract.mjs','tools/bakemono-rinne-wgsl-02/verify-cpu-f32-parity.mjs','tools/bakemono-rinne-wgsl-02/verify-shadow-authority.mjs','tools/bakemono-rinne-wgsl-02/verify-negative-controls.mjs','tools/bakemono-rinne-wgsl-02/webgl-reference.mjs','tools/bakemono-rinne-wgsl-02/qualification-page.html','tools/bakemono-rinne-wgsl-02/qualification-renderer.mjs','tools/bakemono-rinne-wgsl-02/electron-qualification-main.mjs','tools/bakemono-rinne-wgsl-02/electron-qualification-preload.mjs','tools/bakemono-rinne-wgsl-02/run-electron-physical.mjs','tools/bakemono-rinne-wgsl-02/verify-source.mjs','tools/bakemono-rinne-wgsl-02/gate-source.mjs','tools/bakemono-rinne-wgsl-02/finalize-source.mjs','tools/bakemono-rinne-wgsl-02/gate-physical.mjs','tools/bakemono-rinne-wgsl-02/finalize-physical.mjs',CATALOG_REL,SPEC_REL,`${SPEC_REL}.sha256`,'README_TDT_BAKEMONO_RINNE_WGSL_02_APPLIED.md','package.json'];
  const files=implementationFiles.filter(exists).map(rel=>({rel,byteLength:fs.statSync(path.join(ROOT,rel)).size,sha256:fileSha(rel)}));const implBody={schemaVersion:1,schemaId:'tdt.effect.bakemono-rinne.wgsl-02.implementation-manifest.v1',patchId:BKR02_PATCH_ID,parentBundle:PARENT_BUNDLE,parentBundleSha256:PARENT_BUNDLE_SHA,fileCount:files.length,files};const impl={...implBody,selfSha256:sha(implBody)};writeJson(IMPL_REL,impl);
  const finalBody={schemaVersion:1,schemaId:'tdt.effect.bakemono-rinne.wgsl-02.source-final-receipt.v1',patchId:BKR02_PATCH_ID,status:report.status==='PASS'?'SOURCE_BAKED_AWAITING_PHYSICAL_GPU':'SOURCE_FAILED',parentBundle:PARENT_BUNDLE,parentBundleSha256:PARENT_BUNDLE_SHA,parentSourceFinalReceiptSha256:fileSha(PARENT_RECEIPT_REL),sourceGateReportSha256:fileSha(REPORT_REL),implementationManifestSha256:fileSha(IMPL_REL),generatedWgslDigest:generatorManifest.generatedWgslDigest,generatorManifestDigest:generatorManifest.manifestDigest,fixtureManifestDigest:fixtureManifest.manifestDigest,negativeControlReportSha256:fileSha(`${SOURCE_DIR}/source-negative-control-report.json`),physicalGateReportSha256:fileSha(PHYSICAL_REL),gateCount:192,passCount,failCount,physicalGateCount:physicalRows.length,physicalPassCount:0,physicalPendingCount:physicalRows.length,wgslKernelSourceAuthorityClaim:true,compiledKernelAuthorityClaim:false,compatibilityParityClaim:'PENDING_PHYSICAL',outputAuthority:'SHADOW_ONLY',canonicalFinalTextureClaim:false,surfaceRegistryPublishClaim:false,previewAuthorityClaim:false,exportAuthorityClaim:false,r9aCommandGraphClaim:false,nextPatch:'TDT-BAKEMONO-RINNE-WGSL-03'};const final={...finalBody,selfSha256:sha(finalBody)};writeJson(FINAL_REL,final);
  console.log(`${report.status} BKR02 source gates ${passCount}/${rows.length}; physical ${physicalRows.length} PENDING`);if(report.status!=='PASS')for(const r of rows.filter(x=>!x.ok))console.error(`${r.id} FAIL ${r.description}`,r.evidence);
  return {report,finalReceipt:final,implementationManifest:impl,physicalReport:json(PHYSICAL_REL)};
}
if(import.meta.url===pathToFileURL(process.argv[1]).href){const result=await runSourceVerification();if(result.report.status!=='PASS')process.exitCode=1;}
