export const R9AP1_ERRORS=Object.freeze([
  'E_R9AP1_SUMMARY_ONLY_EVIDENCE',
  'E_R9AP1_CHILD_RECEIPT_MISSING',
  'E_R9AP1_FINAL_RECEIPT_INVALID',
  'E_R9AP1_PRODUCT_GRAPH_REQUIRED',
  'E_R9AP1_TICKET_LOST',
]);
