import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
export const ROOT=process.cwd();export const OUT=path.join(ROOT,'artifacts/resample-runtime-01-r9a-p1/source-bake');export const PHYSICAL_OUT=path.join(ROOT,'artifacts/resample-runtime-01-r9a-p1/physical');
export function check(v,code,message,detail=null){if(!v)throw Object.assign(new Error(message),{code,detail});return v;}
export function read(rel){return fs.readFileSync(path.join(ROOT,rel),'utf8');}export function json(rel){return JSON.parse(read(rel));}export function exists(rel){return fs.existsSync(path.join(ROOT,rel));}
export function sha256Bytes(v){return crypto.createHash('sha256').update(v).digest('hex');}export function sha256File(rel){return sha256Bytes(fs.readFileSync(path.join(ROOT,rel)));}
export function canonical(v){if(Array.isArray(v))return v.map(canonical);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])]));if(typeof v==='number')check(Number.isFinite(v),'E_R9AP1_NONFINITE','nonfinite number');return Object.is(v,-0)?0:v;}
export function canonicalJson(v){return JSON.stringify(canonical(v),null,2)+'\n';}export function digestCanonical(v){return sha256Bytes(canonicalJson(v));}
export function seal(v,field='selfSha256'){const b={...v};delete b[field];return Object.freeze({...canonical(b),[field]:digestCanonical(b)});}export function verifySelf(v,field='selfSha256'){if(!v||typeof v[field]!=='string')return false;const b={...v};const e=b[field];delete b[field];return e===digestCanonical(b);}
export function ensureDir(d){fs.mkdirSync(d,{recursive:true});return d;}export function atomicWrite(f,data){ensureDir(path.dirname(f));const t=f+'.tmp-'+process.pid+'-'+crypto.randomBytes(4).toString('hex');const fd=fs.openSync(t,'wx');try{fs.writeFileSync(fd,data);fs.fsyncSync(fd);}finally{fs.closeSync(fd);}fs.renameSync(t,f);try{const dfd=fs.openSync(path.dirname(f),'r');try{fs.fsyncSync(dfd);}finally{fs.closeSync(dfd);}}catch{}}
export function sourceArtifact(n,v){atomicWrite(path.join(OUT,n),canonicalJson(v));return v;}export function physicalArtifact(n,v){atomicWrite(path.join(PHYSICAL_OUT,n),canonicalJson(v));return v;}
export function capture(id,fn){try{return{id,status:'PASS',evidence:fn()??true};}catch(e){return{id,status:'FAIL',errorCode:String(e?.code||'E_R9AP1_SOURCE_FAILURE'),message:String(e?.message||e),detail:e?.detail??null};}}
export async function captureAsync(id,fn){try{return{id,status:'PASS',evidence:(await fn())??true};}catch(e){return{id,status:'FAIL',errorCode:String(e?.code||'E_R9AP1_SOURCE_FAILURE'),message:String(e?.message||e),detail:e?.detail??null};}}
export function expectError(code,fn){try{fn();}catch(e){check(e?.code===code,'E_R9AP1_NEGATIVE_WRONG_CODE','unexpected error',{expected:code,actual:e?.code});return true;}throw Object.assign(new Error('negative control did not fail'),{code:'E_R9AP1_NEGATIVE_DID_NOT_FAIL',detail:{expected:code}});}
export async function expectErrorAsync(code,fn){try{await fn();}catch(e){check(e?.code===code,'E_R9AP1_NEGATIVE_WRONG_CODE','unexpected error',{expected:code,actual:e?.code});return true;}throw Object.assign(new Error('negative control did not fail'),{code:'E_R9AP1_NEGATIVE_DID_NOT_FAIL',detail:{expected:code}});}
export function walk(rootDir){const out=[];if(!fs.existsSync(rootDir))return out;const q=[rootDir];while(q.length){const d=q.pop();for(const e of fs.readdirSync(d,{withFileTypes:true}).sort((a,b)=>b.name.localeCompare(a.name))){const a=path.join(d,e.name);if(e.isDirectory())q.push(a);else out.push(a);}}return out.sort();}
