import crypto from 'node:crypto';
import {check,canonical,digestCanonical} from './lib.mjs';
function compactCanonical(v){return JSON.stringify(canonical(v));}
function sha(v){return crypto.createHash('sha256').update(compactCanonical(v)).digest('hex');}
export function replayEventLedgerR9AP1(ledger){check(ledger?.schemaId==='tdt.ewa.physical-event-ledger.r9a-p1.v1','E_R9AP1_LEDGER_SCHEMA','event ledger schema mismatch');let previous='0'.repeat(64),sequence=1,time=-1;const counts={};const jobs=new Map();for(const event of ledger.events??[]){check(event.sequence===sequence,'E_R9AP1_LEDGER_SEQUENCE','event sequence mismatch',{sequence,actual:event.sequence});check(event.previousSha256===previous,'E_R9AP1_LEDGER_CHAIN','event chain mismatch',{sequence});const body={...event};delete body.selfSha256;check(event.selfSha256===sha(body),'E_R9AP1_LEDGER_SELF_HASH','event self hash mismatch',{sequence});check(event.timestampNs>time,'E_R9AP1_LEDGER_TIME','event time is not monotonic',{sequence});previous=event.selfSha256;time=event.timestampNs;sequence++;counts[event.kind]=(counts[event.kind]??0)+1;const jobId=event.payload?.jobId;if(jobId){const row=jobs.get(jobId)??{semanticEncoder:0,submit:0,fence:0,mapBegin:0,mapEnd:0,counterReadbacks:0,timestampReadbacks:0};if(event.kind==='command-encoder-created'&&event.payload?.layer==='semantic-command-graph')row.semanticEncoder++;if(event.kind==='queue-submit'&&event.payload?.submissionSerial)row.submit++;if(event.kind==='queue-work-done')row.fence++;if(event.kind==='buffer-map-begin')row.mapBegin++;if(event.kind==='buffer-map-end')row.mapEnd++;if(event.kind==='validation-counter-readback')row.counterReadbacks++;if(event.kind==='timestamp-readback')row.timestampReadbacks++;jobs.set(jobId,row);}}
check(previous===ledger.headSha256,'E_R9AP1_LEDGER_HEAD','ledger head mismatch');return{eventCount:(ledger.events??[]).length,headSha256:previous,counts,jobs:Object.fromEntries(jobs)};}
export function replaySingleSubmitR9AP1(ledgerReplay){for(const [jobId,row] of Object.entries(ledgerReplay.jobs)){check(row.semanticEncoder===1,'E_R9AP1_ENCODER_COUNT','job encoder count is not one',{jobId,row});check(row.submit===1,'E_R9AP1_SUBMIT_COUNT','job submit count is not one',{jobId,row});check(row.mapBegin===row.mapEnd,'E_R9AP1_MAP_LIFETIME','map begin/end mismatch',{jobId,row});}return{jobCount:Object.keys(ledgerReplay.jobs).length};}
export function replayCountersR9AP1(raw){check(raw?.schemaId==='tdt.r9a-p1.raw-counter-readback.v1','E_R9AP1_COUNTER_SCHEMA','counter raw schema mismatch');let normalRows=0,faultRows=0;for(const row of raw.rows??[]){check(Array.isArray(row.values)&&row.values.length===32,'E_R9AP1_COUNTER_WIDTH','counter row must contain 32 values');const nonzero=row.values.map((v,i)=>({i,v:Number(v)})).filter(x=>x.v!==0);if(row.faultMode==null){check(nonzero.length===0,'E_R9AP1_COUNTER_NORMAL_NONZERO','normal counter row is nonzero',{row});normalRows++;}else{check(nonzero.length===1,'E_R9AP1_COUNTER_FAULT_EXCLUSIVITY','fault row must increment one counter',{row,nonzero});faultRows++;}}check(normalRows>0&&faultRows>=8,'E_R9AP1_COUNTER_COVERAGE','counter coverage incomplete',{normalRows,faultRows});return{normalRows,faultRows};}
function quantile(values,q){const a=[...values].map(Number).sort((x,y)=>x-y);check(a.length>0&&a.every(Number.isFinite),'E_R9AP1_TIMESTAMP_RAW','timestamp samples invalid');return a[Math.floor((a.length-1)*q)];}
export function replayTimestampsR9AP1(raw){check(raw?.schemaId==='tdt.r9a-p1.raw-timestamp-samples.v1','E_R9AP1_TIMESTAMP_SCHEMA','timestamp raw schema mismatch');const durations=[];for(const batch of raw.rows??[])for(const row of batch.rows??[]){const d=Number(BigInt(row.durationTicks));check(d>=0,'E_R9AP1_TIMESTAMP_RAW','negative duration');durations.push(d);}check(durations.length>=256,'E_R9AP1_TIMESTAMP_SAMPLE_COUNT','insufficient GPU timestamp samples',{count:durations.length});return{sampleCount:durations.length,medianTicks:quantile(durations,.5),p95Ticks:quantile(durations,.95)};}
function linearSlope(values){const n=values.length;check(n>=2,'E_R9AP1_RESIDENCY_SAMPLES','insufficient residency samples');let sx=0,sy=0,sxy=0,sxx=0;for(let i=0;i<n;i++){const y=Number(values[i]);check(Number.isFinite(y),'E_R9AP1_RESIDENCY_SAMPLES','nonfinite residency sample');sx+=i;sy+=y;sxy+=i*y;sxx+=i*i;}return(n*sxy-sx*sy)/(n*sxx-sx*sx||1);}
export function replayResidencyR9AP1(raw){check(raw?.schemaId==='tdt.r9a-p1.residency-raw.v1','E_R9AP1_RESIDENCY_SCHEMA','residency schema mismatch');check(Number(raw.measured)>=1024,'E_R9AP1_RESIDENCY_SAMPLE_COUNT','residency measured jobs below 1024');const tail=(raw.rows??[]).slice(-64);check(tail.length>=64,'E_R9AP1_RESIDENCY_SAMPLES','last 64 residency samples missing');return{privateSlope:linearSlope(tail.map(x=>x.totalPrivateBytes)),workingSetSlope:linearSlope(tail.map(x=>x.totalWorkingSetBytes))};}
export function replayDeviceEpochsR9AP1(raw){check(raw?.schemaId==='tdt.r9a-p1.device-epoch-ledger.v1','E_R9AP1_DEVICE_EPOCH_SCHEMA','device epoch ledger schema mismatch');const losses=(raw.rows??[]).filter(x=>x.kind==='device-lost'||x.payload?.to==='LOST');check(losses.length>=3,'E_R9AP1_DEVICE_LOSS_CYCLES','three device-loss cycles missing',{losses:losses.length});return{lossEvidenceCount:losses.length};}
export function replayPhysicalEvidenceR9AP1({ledger,counters,timestamps,residency,epochs}){const ledgerReplay=replayEventLedgerR9AP1(ledger);return{ledger:ledgerReplay,singleSubmit:replaySingleSubmitR9AP1(ledgerReplay),counters:replayCountersR9AP1(counters),timestamps:replayTimestampsR9AP1(timestamps),residency:replayResidencyR9AP1(residency),epochs:replayDeviceEpochsR9AP1(epochs),rawEvidenceDigest:digestCanonical({ledger,counters,timestamps,residency,epochs})};}
