import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { canonicalBakemonoRinneJson } from '../../app/legacy-runtime/core/compute/qmap_webgpu/bakemono_rinne_contract_receipt.mjs';
import { BKR03_PATCH_ID,BKR03_KERNEL_ID,BKR03_KERNEL_ABI_ID,BKR03_PIPELINE_FAMILY_ID,BKR03_OUTPUT_AUTHORITY,BKR03_LAMBDA2_PROBE_ID,BKR03_STRUCTURE_GATE_ID } from '../../app/legacy-runtime/core/compute/qmap_webgpu/bakemono_rinne_wgsl_03_contract.mjs';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const COMPAT_REL='app/legacy-runtime/core/compute/qmap_webgpu/shaders/bakemono_rinne_fusion_compat_v1.generated.wgsl';
const OUT_REL='app/legacy-runtime/core/compute/qmap_webgpu/shaders/bakemono_rinne_fusion_r1c_gated_v1.generated.wgsl';
const PROBE_TMPL='tools/bakemono-rinne-wgsl-03/templates/lambda2-probe.wgsl.tmpl';
const PROBE_REL='app/legacy-runtime/core/compute/qmap_webgpu/shaders/bakemono_rinne_terminal_lambda2_probe_v1.generated.wgsl';
const MANIFEST_REL='app/legacy-runtime/core/compute/qmap_webgpu/shaders/generated-bakemono-rinne-wgsl-03-manifest.json';
const SOURCE_MANIFEST_REL='artifacts/bakemono-rinne-wgsl-03/source/generated-wgsl-manifest.json';
const sha=(v)=>createHash('sha256').update(v).digest('hex');
const shaJson=(v)=>sha(canonicalBakemonoRinneJson(v));
function canonicalFromCompat(compat){
  let text=compat.replace(/\r\n/g,'\n');
  text=text.replace('// Generated by TDT-BAKEMONO-RINNE-WGSL-02. Do not edit.','// Generated by TDT-BAKEMONO-RINNE-WGSL-03. Do not edit.');
  text=text.replace(/\/\/ kernelId: .*\n/,'// kernelId: '+BKR03_KERNEL_ID+'\n');
  text=text.replace(/\/\/ kernelAbiId: .*\n/,'// kernelAbiId: '+BKR03_KERNEL_ABI_ID+'\n');
  text=text.replace(/\/\/ pipelineFamilyId: .*\n/,'// pipelineFamilyId: '+BKR03_PIPELINE_FAMILY_ID+'\n');
  text=text.replace('// outputAuthority: SHADOW_ONLY','// outputAuthority: '+BKR03_OUTPUT_AUTHORITY+'\n// structureGateId: '+BKR03_STRUCTURE_GATE_ID);
  text=text.replaceAll('BakemonoRinneCompatParams','BakemonoRinneCanonicalParams');
  text=text.replace('coherenceExponentReserved: f32,','coherenceExponent: f32,');
  text=text.replace('  reserved0: u32,\n  reserved1: u32,\n  reserved2: u32,','  tensorProfileEnum: u32,\n  tensorPackingEnum: u32,\n  structureGateEnum: u32,');
  text=text.replace('@group(0) @binding(6) var outputTex: texture_storage_2d<rgba16float, write>;\n@group(0) @binding(7) var<uniform> params: BakemonoRinneCanonicalParams;','@group(0) @binding(6) var terminalR1CTex: texture_2d<f32>;\n@group(0) @binding(7) var outputTex: texture_storage_2d<rgba16float, write>;\n@group(0) @binding(8) var<uniform> params: BakemonoRinneCanonicalParams;');
  text=text.replace('fn finite3(v: vec3<f32>) -> bool {\n  return finite1(v.x) && finite1(v.y) && finite1(v.z);\n}','fn finite3(v: vec3<f32>) -> bool {\n  return finite1(v.x) && finite1(v.y) && finite1(v.z);\n}\n\nfn finite4(v: vec4<f32>) -> bool {\n  return finite1(v.x) && finite1(v.y) && finite1(v.z) && finite1(v.w);\n}');
  text=text.replace('  let edge = textureLoad(edgeTex, pixel, 0).r;','  let edge = textureLoad(edgeTex, pixel, 0).r;\n  let terminalR1C = textureLoad(terminalR1CTex, pixel, 0);\n  let coherence = clamp(terminalR1C.b, 0.0, 1.0);\n  let structureEdge = clamp(terminalR1C.a, 0.0, 1.0);\n  let structureGate = select(0.0, pow(coherence, params.coherenceExponent) * structureEdge, finite4(terminalR1C));');
  text=text.replace('  let k = clamp(q * s * params.power, 0.0, 1.0);','  let k = clamp(q * s * params.power * structureGate, 0.0, 1.0);');
  if(!text.includes('pow(coherence, params.coherenceExponent) * structureEdge'))throw new Error('structure gate injection failed');
  if((text.match(/\* structureGate/g)||[]).length!==1)throw new Error('structure gate must be applied exactly once');
  return text.endsWith('\n')?text:text+'\n';
}
export function renderBakemonoRinneWgsl03(){const compat=fs.readFileSync(path.join(ROOT,COMPAT_REL),'utf8');return canonicalFromCompat(compat);}
export function renderLambda2ProbeWgsl03(){let text=fs.readFileSync(path.join(ROOT,PROBE_TMPL),'utf8').replaceAll('{{PROBE_ID}}',BKR03_LAMBDA2_PROBE_ID).replace(/\r\n/g,'\n');return text.endsWith('\n')?text:text+'\n';}
export function writeBakemonoRinneWgsl03GeneratedSources(){const canonicalA=renderBakemonoRinneWgsl03(),canonicalB=renderBakemonoRinneWgsl03(),probeA=renderLambda2ProbeWgsl03(),probeB=renderLambda2ProbeWgsl03();if(canonicalA!==canonicalB||probeA!==probeB)throw new Error('WGSL-03 generator nondeterministic');const compat=fs.readFileSync(path.join(ROOT,COMPAT_REL));const body={schemaVersion:1,patchId:BKR03_PATCH_ID,kernelId:BKR03_KERNEL_ID,kernelAbiId:BKR03_KERNEL_ABI_ID,pipelineFamilyId:BKR03_PIPELINE_FAMILY_ID,compatibilityKernelDigest:sha(compat),generatedWgslDigest:sha(canonicalA),probeWgslDigest:sha(probeA),canonicalByteLength:Buffer.byteLength(canonicalA),probeByteLength:Buffer.byteLength(probeA),generatorSourceDigest:sha(fs.readFileSync(fileURLToPath(import.meta.url))),probeTemplateDigest:sha(fs.readFileSync(path.join(ROOT,PROBE_TMPL))),structureGateId:BKR03_STRUCTURE_GATE_ID};const manifest=Object.freeze({...body,manifestDigest:shaJson(body)});for(const rel of [OUT_REL,PROBE_REL,MANIFEST_REL,SOURCE_MANIFEST_REL])fs.mkdirSync(path.dirname(path.join(ROOT,rel)),{recursive:true});fs.writeFileSync(path.join(ROOT,OUT_REL),canonicalA);fs.writeFileSync(path.join(ROOT,PROBE_REL),probeA);fs.writeFileSync(path.join(ROOT,MANIFEST_REL),JSON.stringify(manifest,null,2)+'\n');fs.writeFileSync(path.join(ROOT,SOURCE_MANIFEST_REL),JSON.stringify(manifest,null,2)+'\n');return {canonical:canonicalA,probe:probeA,manifest};}
if(import.meta.url===pathToFileURL(process.argv[1]).href){const r=writeBakemonoRinneWgsl03GeneratedSources();console.log(`PASS WGSL-03 canonical=${r.manifest.generatedWgslDigest} probe=${r.manifest.probeWgslDigest}`);}
