export const PATCH='TDT-RESAMPLE-RUNTIME-01-R11';
export const SOURCE_STATE='RESAMPLE_RUNTIME_R11_ATTESTATION_HARNESS_SOURCE_BAKED_AWAITING_R10_PRODUCTION_RELEASE';
export const FINAL_STATE='RESAMPLE_RUNTIME_R11_INSTALLED_RUNTIME_ATTESTATION_AND_QUARANTINE_SEALED';
export const SOURCE_PASS=148;export const INSTALLED_PENDING=228;
