import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto';
export const ROOT=process.cwd(); export const OUT=path.join(ROOT,'artifacts/build-lock-01-r2/source-bake'); export const WIN32_OUT=path.join(ROOT,'artifacts/build-lock-01-r2/win32');
export function check(v,code,message,detail=null){if(!v)throw Object.assign(new Error(message),{code,detail});return v;}
export function read(rel){return fs.readFileSync(path.join(ROOT,rel),'utf8');} export function json(rel){return JSON.parse(read(rel));} export function exists(rel){return fs.existsSync(path.join(ROOT,rel));}
export function sha256Bytes(v){return crypto.createHash('sha256').update(v).digest('hex');} export function sha256File(rel){return sha256Bytes(fs.readFileSync(path.join(ROOT,rel)));}
export function canonical(v){if(Array.isArray(v))return v.map(canonical);if(v&&typeof v==='object')return Object.fromEntries(Object.keys(v).sort().map(k=>[k,canonical(v[k])]));if(typeof v==='number')check(Number.isFinite(v),'E_BUILD_LOCK_R2_FINAL_CHILD_MISSING','nonfinite number');return Object.is(v,-0)?0:v;}
export function canonicalJson(v){return JSON.stringify(canonical(v),null,2)+'\n';} export function digestCanonical(v){return sha256Bytes(canonicalJson(v));}
export function seal(v,field='selfSha256'){const b={...v};delete b[field];return Object.freeze({...canonical(b),[field]:digestCanonical(b)});} export function verifySelf(v,field='selfSha256'){if(!v||typeof v[field]!=='string')return false;const b={...v};const e=b[field];delete b[field];return e===digestCanonical(b);}
export function ensureDir(d){fs.mkdirSync(d,{recursive:true});return d;} export function atomicWrite(f,data){ensureDir(path.dirname(f));const t=f+'.tmp-'+process.pid;const fd=fs.openSync(t,'w');try{fs.writeFileSync(fd,data);fs.fsyncSync(fd);}finally{fs.closeSync(fd);}fs.renameSync(t,f);try{const dfd=fs.openSync(path.dirname(f),'r');try{fs.fsyncSync(dfd);}finally{fs.closeSync(dfd);}}catch{}}
export function sourceArtifact(n,v){atomicWrite(path.join(OUT,n),canonicalJson(v));return v;} export function win32Artifact(n,v){atomicWrite(path.join(WIN32_OUT,n),canonicalJson(v));return v;}
export function capture(id,fn){try{return{id,status:'PASS',evidence:fn()??true};}catch(e){return{id,status:'FAIL',errorCode:String(e?.code||'E_BUILD_LOCK_R2_FINAL_CHILD_MISSING'),message:String(e?.message||e),detail:e?.detail??null};}}
export function expectError(code,fn){try{fn();}catch(e){check(e?.code===code,'E_BUILD_LOCK_R2_FINAL_CHILD_MISSING','unexpected error code',{expected:code,actual:e?.code});return true;}throw Object.assign(new Error('negative control did not fail'),{code:'E_BUILD_LOCK_R2_FINAL_CHILD_MISSING',detail:{expected:code}});}
export function walk(rootDir){const out=[];if(!fs.existsSync(rootDir))return out;const q=[rootDir];while(q.length){const d=q.pop();for(const e of fs.readdirSync(d,{withFileTypes:true}).sort((a,b)=>b.name.localeCompare(a.name))){const a=path.join(d,e.name);if(e.isDirectory())q.push(a);else out.push(a);}}return out.sort();}
