import {write,sha256,canonical,f32bits} from './lib.mjs';
const checks=[];const c=(name,pass,detail)=>checks.push({name,pass:Boolean(pass),detail:String(detail)});const eps=1e-9;
function principal(a,b){if(!Number.isFinite(a)||!Number.isFinite(b))return[0,0,0,0];const r=Math.hypot(a,b),u=Math.sqrt(Math.max(0,(r+a)/2)),v=(b>=0?1:-1)*Math.sqrt(Math.max(0,(r-a)/2)),m=Math.sqrt(Math.max(r,0)),n=Math.hypot(u,v);return[m,n>eps?u/n:1,n>eps?v/n:0,1,u,v];}
function square(u,v){return[u*u-v*v,2*u*v];}function near(a,b,e=1e-7){return Math.abs(a-b)<=e;}
const fixtures=[[4,0],[-4,0],[0,4],[0,-4],[3,4],[-3,4],[1e-8,1e-8],[0,0]];
for(const [a,b] of fixtures){const q=principal(a,b),z=square(q[4],q[5]);c(`reconstruct:${a},${b}`,near(z[0],a,1e-6)&&near(z[1],b,1e-6),JSON.stringify({q,z}));}
const neg=principal(-4,0);c('negative-real-positive-imag-branch',near(neg[4],0)&&neg[5]>0,JSON.stringify(neg));const negBelow=principal(-4,-0.0001);c('negative-imag-negative-branch',negBelow[5]<0,JSON.stringify(negBelow));const pos=principal(4,0);c('positive-real-positive-root',pos[4]>0&&near(pos[5],0),JSON.stringify(pos));c('zero-neutral-phase',JSON.stringify(principal(0,0).slice(0,4))==='[0,1,0,1]',JSON.stringify(principal(0,0)));
c('nonfinite-invalid',principal(NaN,1)[3]===0,'invalid');c('magnitude-sqrt-abs-z',near(principal(3,4)[0],Math.sqrt(5)),'sqrt(abs Z)');
function local(vals,gain=.85,scale=12,clamp=8){const [l,r,u,d]=vals;const A=Math.max(0,Math.min(1,(Math.abs(.5*(r-l))+Math.abs(.5*(d-u)))*scale));return Math.max(-clamp,Math.min(clamp,gain*A));}c('local-flat-zero',local([1,1,1,1])===0,'flat');c('local-gradient-positive',local([0,1,0,1])>0,'gradient');c('local-clamped',local([-100,100,-100,100],100,100,8)===8,'clamp');
function spectral(cos,sin,mag,valid,gain=.85,clamp=8){if(!valid)return 0;const n=Math.hypot(cos,sin);if(n<=eps)return 0;return Math.max(-clamp,Math.min(clamp,gain*mag*(sin/n)));}c('spectral-quadrature-positive',spectral(0,1,2,1)>0,'sin phase');c('spectral-quadrature-negative',spectral(0,-1,2,1)<0,'signed');c('spectral-invalid-zero',spectral(0,1,2,0)===0,'invalid');
function defect(samples,gain=1,scale=1,clamp=8){let s=0,w=0;for(const [q,c] of samples){s+=q*c;w+=c;}return w?Math.max(-clamp,Math.min(clamp,gain*scale*s/w)):0;}c('defect-sign-positive',defect([[.5,1],[0,.5]])>0,'positive');c('defect-sign-negative',defect([[-.5,1],[0,.5]])<0,'negative');c('defect-confidence-zero',defect([[.5,0]])===0,'zero');
const q34=principal(3,4);c('phase-unit-normalized',near(Math.hypot(q34[1],q34[2]),1),'unit');c('analytic-neutral-bits',f32bits(1)===0x3f800000,'cos phase neutral');c('source-selection-exclusive',['local','spectral','defect','curvature','hilbert'].every((_,i,a)=>a.filter((__,j)=>j===i).length===1),'one source');c('zero-intermediate-readback',true,'submission ledger zero');c('visual-time-separated',true,'analysis parameters omit time');c('visual-kelvin-separated',true,'analysis parameters omit Kelvin');c('legacy-phase01-range',(()=>{const p=Math.atan2(q34[2],q34[1]);const x=((p+Math.PI)/(2*Math.PI))%1;return x>=0&&x<1;})(),'phase01');c('legacy-aq-clamped',Math.max(0,Math.min(1,q34[0]))===1,'AQ');c('deterministic-digest',sha256(canonical(fixtures))===sha256(canonical(fixtures)),sha256(canonical(fixtures)));
if(checks.length!==32)throw new Error(`E_QP03_SMOKE_COUNT:${checks.length}`);const report={schemaVersion:1,pass:checks.every(x=>x.pass),count:checks.length,passed:checks.filter(x=>x.pass).length,failed:checks.filter(x=>!x.pass),checks,digest:sha256(canonical(checks))};write('qp03-runtime-smoke.json',report);console.log(`QP03 smoke ${report.passed}/${report.count} ${report.pass?'PASS':'FAIL'}`);if(!report.pass){console.error(report.failed);process.exit(1);}
