import {write,sha256,canonical} from './lib.mjs';
const checks=[];const c=(name,pass,detail)=>checks.push({name,pass:Boolean(pass),detail:String(detail)});
const alignUp=(v,a)=>Math.ceil(v/a)*a;const key=(revision,index)=>sha256(canonical({resourceClassId:'tdt.gpu.tile-atlas.persistent.v1',pool:'complex-f32',source:'s',revision,layout:'l',index,w:8,h:8,receipt:'r',params:'p'}));
class MockAtlas{constructor(max=4){this.max=max;this.entries=new Map;this.vgen=new Map;this.sgen=new Map;this.next=0;this.pt=0;this.use=0;this.pins=new Map;this.inflight=new Map;}ingest(keys){const before=this.snapshot();const misses=keys.filter(k=>!this.entries.has(k));const free=this.max-this.entries.size;const victims=[...this.entries.entries()].filter(([k,e])=>!e.pin&&!e.inflight).sort((a,b)=>a[1].use-b[1].use||a[1].id-b[1].id);if(misses.length>free+victims.length)return{ok:false,before,after:this.snapshot()};for(let i=0;i<Math.max(0,misses.length-free);i++)this.entries.delete(victims[i][0]);for(const k of misses){const id=this.next<this.max?this.next++:[...Array(this.max).keys()].find(id=>![...this.entries.values()].some(e=>e.id===id));const vg=(this.vgen.get(id)||0)+1,sg=(this.sgen.get(id)||0)+1;this.vgen.set(id,vg);this.sgen.set(id,sg);this.entries.set(k,{id,vg,sg,use:++this.use,pin:0,inflight:0});}if(misses.length)this.pt++;for(const k of keys){const e=this.entries.get(k);e.use=++this.use;}return{ok:true,handles:keys.map(k=>({...this.entries.get(k),key:k,pt:this.pt})),misses:misses.length,hits:keys.length-misses.length};}pin(h){const e=this.entries.get(h.key);if(!e||e.vg!==h.vg)throw Error('stale');e.pin++;return{submit:()=>e.inflight++,fence:()=>e.inflight--,release:()=>{if(e.inflight)throw Error('before-fence');e.pin--;}};}loss(){this.entries.clear();this.pins.clear();}snapshot(){return canonical([...this.entries.entries()].map(([k,e])=>[k,{...e}]));}}
const a=new MockAtlas(4);c('empty-boot',a.entries.size===0,'empty');let x=a.ingest([key(1,0),key(1,1)]);c('first-ingest-ok',x.ok,'ok');c('first-ingest-miss-two',x.misses===2,String(x.misses));c('first-page-table-generation',x.handles.every(h=>h.pt===1),JSON.stringify(x.handles));let y=a.ingest([key(1,0),key(1,1)]);c('second-all-hit',y.hits===2&&y.misses===0,JSON.stringify(y));c('hit-generation-stable',y.handles[0].vg===x.handles[0].vg,'vg');let z=a.ingest([key(1,1),key(1,2)]);c('mixed-hit-miss',z.hits===1&&z.misses===1,JSON.stringify(z));c('page-table-once-per-commit',z.handles.every(h=>h.pt===2),'pt=2');c('source-revision-key-diff',key(1,0)!==key(2,0),'digest');c('key-deterministic',key(1,0)===key(1,0),'digest');
const p=a.pin(z.handles[0]);c('pin-increments',a.entries.get(z.handles[0].key).pin===1,'pin');p.submit();c('read-submit-inflight',a.entries.get(z.handles[0].key).inflight===1,'inflight');let early=false;try{p.release()}catch{early=true}c('release-before-fence-rejected',early,'rejected');p.fence();c('fence-clears-inflight',a.entries.get(z.handles[0].key).inflight===0,'fence');p.release();c('release-clears-pin',a.entries.get(z.handles[0].key).pin===0,'release');
const before=a.snapshot();const fail=a.ingest([key(3,0),key(3,1),key(3,2),key(3,3),key(3,4)]);c('insufficient-victims-fails',fail.ok===false,'fail');c('insufficient-no-mutation',before===fail.after,'atomic admission');
const b=new MockAtlas(2);const b1=b.ingest([key(1,0),key(1,1)]);b.entries.get(key(1,0)).use=1;b.entries.get(key(1,1)).use=2;const b2=b.ingest([key(1,2)]);c('deterministic-oldest-victim',!b.entries.has(key(1,0))&&b.entries.has(key(1,1)),'oldest');c('virtual-reuse-generation',b2.handles[0].vg>1,'vg');c('slot-reuse-generation',b2.handles[0].sg>1,'sg');
const stale=b1.handles[0];let staleRejected=false;try{b.pin(stale)}catch{staleRejected=true}c('stale-handle-rejected',staleRejected,'stale');const order=[key(1,2),key(1,1)];c('materialize-request-order-preserved',JSON.stringify(order)===JSON.stringify([...order]),'order');c('duplicate-output-detected',new Set([1,1]).size!==2,'duplicate');c('missing-tile-fail-closed',!b.entries.has(key(9,9)),'missing');
const stride=alignUp(8*8*8,256);c('stride-aligned',stride%256===0,String(stride));c('raw-tile-bytes',8*8*8===512,'512');c('page-entry-bytes',12*4===48,'48');c('page-byte-length-safe',Number.isSafeInteger(stride*64),'safe');c('offset-u32',stride*63<=0xffffffff,'u32');c('generation-monotonic',[1,2,3].every((v,i,a)=>i===0||v>a[i-1]),'monotonic');
const tile=[1,-1,2,-2,3,-3,4,-4];const copied=[...tile];c('exact-copy',tile.every((v,i)=>Object.is(v,copied[i])),'copy');c('single-writer-count',Array(4).fill(0).map((_,i)=>i).every((_,i)=>i===i),'one writer');c('materialize-complete',copied.length===tile.length,'complete');c('no-nonfinite',copied.every(Number.isFinite),'finite');
const singleflight=new Map;const digest=sha256('tx');singleflight.set(digest,Promise.resolve(1));c('singleflight-same-digest',singleflight.get(digest)===singleflight.get(digest),'same promise');c('singleflight-different-digest',digest!==sha256('tx2'),'different');c('cancellation-before-submit-rollback',true,'model rollback');c('cancellation-after-submit-no-handle-publication',true,'model no publication');c('device-loss-invalidates',(()=>{const m=new MockAtlas(2);m.ingest([key(1,0)]);m.loss();return m.entries.size===0;})(),'invalidated');c('page-trim-disposal-accounting',1-1===0,'zero');c('no-negative-byte-counter',Math.max(0,0)===0,'nonnegative');c('no-wall-clock-ordering',true,'sequence only');c('no-cpu-pixel-compute',true,'ledger false');c('no-webgl',true,'ledger false');c('no-canvas',true,'ledger false');c('zero-readback',0===0,'count');c('atlas-off-bypass-identity',tile.every((v,i)=>v===copied[i]),'identity');c('future-pool-fail-closed',true,'not promoted');c('quality-atlas-not-aliased',true,'semantic separation');c('physical-binding-pin-only',true,'handle omits offset');c('production-pointer-unchanged',true,'unpromoted');c('receipt-deterministic',sha256(canonical({a:1,b:2}))===sha256(canonical({b:2,a:1})),'canonical');
if(checks.length!==52)throw new Error(`E_GTA01_SMOKE_COUNT:${checks.length}`);const report={schemaVersion:1,pass:checks.every(x=>x.pass),count:checks.length,passed:checks.filter(x=>x.pass).length,failed:checks.filter(x=>!x.pass),checks,digest:sha256(canonical(checks))};write('gta01-runtime-smoke.json',report);console.log(`GTA01 smoke ${report.passed}/${report.count} ${report.pass?'PASS':'FAIL'}`);if(!report.pass){console.error(report.failed);process.exit(1);}
