import fs from 'node:fs';import path from 'node:path';import {ROOT,ARTIFACT_DIR,shaFile,readJson,writeArtifact} from './lib.mjs';const rels=['app/legacy-runtime/core/compute/qmap_webgpu/ewa_kernel_contract_v4.mjs','app/legacy-runtime/core/compute/qmap_webgpu/ewa_aniso_params_v4.mjs','app/legacy-runtime/core/compute/qmap_webgpu/ewa_tiled_profile_r6.mjs','app/legacy-runtime/core/compute/qmap_webgpu/ewa_kernel_receipt_r6.mjs','app/legacy-runtime/core/compute/qmap_webgpu/ewa_parity_runtime_r6.mjs','app/legacy-runtime/core/compute/qmap_webgpu/ewa_aniso_tile.mjs','app/legacy-runtime/core/compute/qmap_webgpu/ewa_aniso_contract.mjs','app/legacy-runtime/core/compute/qmap_webgpu/deltaK_stack_autoEWA.mjs','app/legacy-runtime/core/compute/qmap_webgpu/shaders/ewa_aniso_tile_r4_r6.wgsl','app/legacy-runtime/core/compute/qmap_webgpu/shaders/ewa_aniso_tile_r6_r6.wgsl','app/legacy-runtime/core/compute/qmap_webgpu/shaders/ewa_aniso_tile_validation_r4_r6.wgsl','app/legacy-runtime/core/compute/qmap_webgpu/shaders/ewa_aniso_tile_validation_r6_r6.wgsl','app/legacy-runtime/core/compute/qmap_webgpu/shaders/ewa_aniso_reference_v5_r6.wgsl','app/legacy-runtime/core/compute/qmap_webgpu/shaders/ewa_generated_manifest_r6.json'];const files=rels.map(r=>({relativePath:r,sha256:shaFile(r),bytes:fs.statSync(path.join(ROOT,r)).size})),gate=readJson('artifacts/resample-runtime-01-r6/source-bake/TDT_RESAMPLE_RUNTIME_01_R6_SOURCE_GATE.json'),manifest=readJson('app/legacy-runtime/core/compute/qmap_webgpu/shaders/ewa_generated_manifest_r6.json');const receipt={schemaVersion:1,patchId:'TDT-RESAMPLE-RUNTIME-01-R6',state:gate.state,counts:gate.counts,parameterAbiId:'tdt.delta-k-ewa.params.v4',parameterAbiVersion:65550,parameterBytes:96,kernelContractId:'tdt.ewa.kernel-contract.r6.v1',kernelId:'tdt.ewa.ellipse.phase-correct-parametric-r6.v1',generatedManifestId:manifest.manifestId,phaseConventionId:'tdt.ewa.source-lattice.pixel-center-v2',phaseConventionEnum:2,borderId:'tdt.ewa.border.clamp-extension-logical-distance-v1',borderEnum:1,defaultKernelSharpness:1.65,defaultKernelTaperExponent:1,generatedOutputCount:5,files,productionPointerMutated:false,physicalGpuClaimed:false,packagedElectronClaimed:false,nextAuthority:'TDT-RESAMPLE-RUNTIME-01-R7'};writeArtifact('TDT_RESAMPLE_RUNTIME_01_R6_FINAL_RECEIPT.json',receipt);const md=`# TDT-RESAMPLE-RUNTIME-01-R6 Applied

- State: \`${receipt.state}\`
- ABI: \`${receipt.parameterAbiId}\` / ${receipt.parameterBytes} bytes
- Kernel: \`${receipt.kernelId}\`
- Generated outputs: ${receipt.generatedOutputCount}
- Gates: ${gate.counts.PASS} PASS / ${gate.counts.DEFERRED} DEFERRED / ${gate.counts.FAIL||0} FAIL
- Production Pointer mutated: false
- Physical GPU claimed: false
- Next authority: \`${receipt.nextAuthority}\`
`;fs.writeFileSync(path.join(ROOT,'README_TDT_RESAMPLE_RUNTIME_01_R6_APPLIED.md'),md);console.log(`PASS R6 finalize ${files.length} authoritative files`);
