
import { generateAuthority, seal } from '../../app/features/resample-runtime/r13a/crypto-utils.mjs';
import { createKeyRegistryV2 } from '../../app/features/resample-runtime/r13a/key-registry-v2.mjs';
import { createRolloutPlanV2 } from '../../app/features/resample-runtime/r13a/rollout-plan-v2.mjs';
import { createFleetLedgerV2, appendFleetLedgerV2 } from '../../app/features/resample-runtime/r13a/fleet-ledger-v2.mjs';
import { createInstallationAdmission } from '../../app/features/resample-runtime/r13a/installation-admission.mjs';
import { issueUpdateLeaseV2 } from '../../app/features/resample-runtime/r13a/update-lease-v2.mjs';
import { createLeaseClaim } from '../../app/features/resample-runtime/r13a/lease-claim.mjs';
import { issueDrainPermit } from '../../app/features/resample-runtime/r13a/drain-permit.mjs';
import { createLocalTransitionBinding } from '../../app/features/resample-runtime/r13a/local-transition-binding.mjs';
import { createLocalCompletionReceipt } from '../../app/features/resample-runtime/r13a/local-completion-receipt.mjs';
import { createPostUpdateEvidenceV2 } from '../../app/features/resample-runtime/r13a/evidence-envelope-v2.mjs';
import { createEvidenceAcknowledgement } from '../../app/features/resample-runtime/r13a/evidence-acknowledgement.mjs';
import { computeExactAggregateV2 } from '../../app/features/resample-runtime/r13a/exact-aggregator-v2.mjs';
import { createPrivacyViewV2 } from '../../app/features/resample-runtime/r13a/privacy-view-v2.mjs';
import { IDS, R12A_CHILD_KEYS } from '../../app/features/resample-runtime/r13a/r13a-contract.mjs';
export function createValidFixture() {
  const authorities={plan:generateAuthority('plan-1'),lease:generateAuthority('lease-1'),permit:generateAuthority('permit-1'),installation:generateAuthority('installation-1'),ack:generateAuthority('ack-1'),containment:generateAuthority('containment-1'),final:generateAuthority('final-1')};
  const registry=createKeyRegistryV2([
    {role:'plan',keyId:authorities.plan.keyId,publicKeyPem:authorities.plan.publicKeyPem,effectiveGeneration:1},
    {role:'lease',keyId:authorities.lease.keyId,publicKeyPem:authorities.lease.publicKeyPem,effectiveGeneration:1},
    {role:'drain-permit',keyId:authorities.permit.keyId,publicKeyPem:authorities.permit.publicKeyPem,effectiveGeneration:1},
    {role:'installation',keyId:authorities.installation.keyId,publicKeyPem:authorities.installation.publicKeyPem,effectiveGeneration:1},
    {role:'evidence-ack',keyId:authorities.ack.keyId,publicKeyPem:authorities.ack.publicKeyPem,effectiveGeneration:1},
    {role:'containment',keyId:authorities.containment.keyId,publicKeyPem:authorities.containment.publicKeyPem,effectiveGeneration:1},
    {role:'fleet-final',keyId:authorities.final.keyId,publicKeyPem:authorities.final.publicKeyPem,effectiveGeneration:1},
  ]);
  const plan=createRolloutPlanV2({rolloutId:'ab'.repeat(24),planId:'cd'.repeat(16),planGeneration:1,targetBuildId:'build-target',targetPackageContentId:'1'.repeat(64),previousBuildId:'build-previous',previousPackageContentId:'2'.repeat(64),r10aFinalReleaseReceiptSha256:'3'.repeat(64),r11aInstalledReceiptSha256:'4'.repeat(64),r12aInstalledReceiptSha256:'5'.repeat(64),operatorApprovalDigest:'6'.repeat(64),expiresAt:'2030-01-01T00:00:00.000Z'},authorities.plan);
  const admission=createInstallationAdmission({rolloutId:plan.rolloutId,planDigest:plan.planSha256,installationRolloutPseudonym:'install-pseudo-1',enrollmentKeyDigest:'7'.repeat(64)},authorities.installation);
  const transaction={updateTransactionId:'tx-0001',sourceBuildId:'build-previous',sourcePackageContentId:plan.previousPackageContentId,targetBuildId:plan.targetBuildId,targetPackageContentId:plan.targetPackageContentId,expectedProductionPointerGeneration:3,expectedProductionPointerRawSha256:'8'.repeat(64),expectedLocalPointerGeneration:2,expectedLocalPointerRawSha256:'9'.repeat(64)};
  const lease=issueUpdateLeaseV2({rolloutId:plan.rolloutId,planDigest:plan.planSha256,planGeneration:1,ringId:'RING-0',installationRolloutPseudonym:admission.installationRolloutPseudonym,sourceBuildId:transaction.sourceBuildId,sourcePackageContentId:transaction.sourcePackageContentId,targetBuildId:transaction.targetBuildId,targetPackageContentId:transaction.targetPackageContentId,expectedProductionPointerGeneration:3,expectedProductionPointerRawSha256:transaction.expectedProductionPointerRawSha256,expectedLocalPointerGeneration:2,expectedLocalPointerRawSha256:transaction.expectedLocalPointerRawSha256,notBefore:'2025-01-01T00:00:00.000Z',expiresAt:'2030-01-01T00:00:00.000Z'},authorities.lease);
  const claim=createLeaseClaim({rolloutId:plan.rolloutId,leaseSha256:lease.leaseSha256,installationRolloutPseudonym:admission.installationRolloutPseudonym,updateTransactionId:transaction.updateTransactionId},authorities.installation,new Map());
  const permit=issueDrainPermit({rolloutId:plan.rolloutId,planDigest:plan.planSha256,ringId:'RING-0',leaseSha256:lease.leaseSha256,claimSha256:claim.claimSha256,updateTransactionId:transaction.updateTransactionId,activeClaimCount:1,activeDrainCount:0,expiresAt:'2030-01-01T00:00:00.000Z'},authorities.permit);
  const binding=createLocalTransitionBinding({rolloutId:plan.rolloutId,planDigest:plan.planSha256,planGeneration:1,ringId:'RING-0',installationRolloutPseudonym:admission.installationRolloutPseudonym,leaseSha256:lease.leaseSha256,claimSha256:claim.claimSha256,permitSha256:permit.permitSha256,updateTransactionId:transaction.updateTransactionId,sourcePackageContentId:transaction.sourcePackageContentId,targetPackageContentId:transaction.targetPackageContentId,expectedProductionPointerGeneration:3,expectedProductionPointerRawSha256:transaction.expectedProductionPointerRawSha256,expectedLocalPointerGeneration:2,expectedLocalPointerRawSha256:transaction.expectedLocalPointerRawSha256,journalIntentEntrySha256:'a'.repeat(64)},authorities.installation);
  const childFields={transitionAdmission:'receiptSha256',stagingReceipt:'receiptSha256',drainReceipt:'receiptSha256',activationIntent:'intentSha256',localPointerCasReceipt:'receiptSha256',relaunchRequest:'requestSha256',launchAck:'ackSha256',reattestationReceipt:'receiptSha256',commitReceipt:'receiptSha256',recoveryMatrixReceipt:'receiptSha256'};
  const children={}; for(const key of R12A_CHILD_KEYS) children[key]=seal({schemaVersion:1,schemaId:`fixture.${key}`,updateTransactionId:transaction.updateTransactionId},childFields[key]);
  const r12aFinal=seal({schemaVersion:1,schemaId:'tdt.resample-runtime.installed-final-receipt.r12a.v1',state:'RESAMPLE_RUNTIME_R12A_ATOMIC_UPDATE_MAIN_INTEGRATION_AND_INTERRUPTED_RECOVERY_SEALED_AWAITING_R13A',updateTransactionId:transaction.updateTransactionId,localActivationPointerCasCount:1,productionPointerMutated:false,crossGenerationAssetCount:0,childDigests:Object.fromEntries(R12A_CHILD_KEYS.map((key)=>[key,children[key][childFields[key]]]))},'receiptSha256');
  const completion=createLocalCompletionReceipt({binding,r12aFinalReceipt:r12aFinal,r12aChildren:children,targetBuildId:plan.targetBuildId,targetPackageContentId:plan.targetPackageContentId,r11aTargetSessionDigest:'b'.repeat(64)},authorities.installation);
  const evidence=createPostUpdateEvidenceV2({rolloutId:plan.rolloutId,planDigest:plan.planSha256,ringId:'RING-0',installationRolloutPseudonym:admission.installationRolloutPseudonym,localCompletionSha256:completion.completionSha256,evidenceSequence:1,coarseWindowStart:'2026-01-01T00:00:00.000Z',coarseWindowEnd:'2026-01-02T00:00:00.000Z',buildId:plan.targetBuildId,packageContentId:plan.targetPackageContentId,adapterFamilyBucket:'nvidia-ampere',driverMajorBucket:'580',exposureDurationBucket:'1d',metrics:{activationFailure:false,deviceLoss:false,rendererCrash:false,gpuProcessCrash:false}},authorities.installation);
  const ack=createEvidenceAcknowledgement({...evidence,outcome:'ACCEPTED',acceptedSetGeneration:1},authorities.ack);
  const aggregate=computeExactAggregateV2({rolloutId:plan.rolloutId,planDigest:plan.planSha256,ringId:'RING-0',admittedInstallations:[admission.installationRolloutPseudonym],evidence:[evidence],acknowledgedEvidenceDigests:new Set([evidence.evidenceSha256])});
  const privacy=createPrivacyViewV2([evidence],{minimumK:5});
  let ledger=createFleetLedgerV2(plan.rolloutId); ledger=appendFleetLedgerV2(ledger,{eventType:'PLAN_ADMITTED',generation:1,evidenceDigest:plan.planSha256}); ledger=appendFleetLedgerV2(ledger,{eventType:'LOCAL_COMPLETED',ringId:'RING-0',generation:1,evidenceDigest:completion.completionSha256});
  const ringDecisions=Array.from({length:6},(_,i)=>seal({schemaVersion:2,schemaId:IDS.ringDecision,rolloutId:plan.rolloutId,planDigest:plan.planSha256,currentRingId:`RING-${i}`,nextRingId:i===5?'RING-5':`RING-${i+1}`,action:i===5?'COMPLETE':'ADVANCE',aggregateSha256:aggregate.aggregateSha256},'decisionSha256'));
  return {authorities,keyRegistry:registry,plan,fleetLedger:ledger,installationAdmissions:[admission],leases:[lease],claims:[claim],drainPermits:[permit],bindings:[binding],r12aTransactions:{[transaction.updateTransactionId]:transaction},localCompletions:[completion],evidence:[evidence],acknowledgements:[ack],exactAggregate:aggregate,privacyReport:privacy,ringDecisions,currentRingId:'RING-0',now:'2026-01-03T00:00:00.000Z',productionPointerMutationCount:0,localActivationPointerMutationCount:0,unknownInstallationCount:0,unacknowledgedEvidenceLossCount:0,transaction,children,r12aFinal,binding,completion,evidenceOne:evidence,ackOne:ack};
}
