export const R9_PATCH_ID = 'TDT-RESAMPLE-RUNTIME-01-R9';
export const R9_HARNESS_ID = 'tdt.ewa.physical-qualification-harness.r9.v1';
export const R9_EVIDENCE_SCHEMA_ID = 'tdt.ewa.physical-evidence.r9.v1';
export const R9_SOURCE_STATE = 'RESAMPLE_RUNTIME_R9_PHYSICAL_HARNESS_SOURCE_BAKED_AWAITING_WINDOWS_EXECUTION';
export const R9_RUNNING_STATE = 'RESAMPLE_RUNTIME_R9_PHYSICAL_RUN_IN_PROGRESS';
export const R9_ACCEPTED_STATE = 'RESAMPLE_RUNTIME_R9_PHYSICAL_GPU_AND_PACKAGED_EXECUTION_SEALED_AWAITING_R10';
export const R9_REJECTED_STATE = 'RESAMPLE_RUNTIME_R9_PHYSICAL_CANDIDATE_REJECTED';
export const R9_PRIMARY_PLATFORM = Object.freeze({ platform: 'win32', arch: 'x64', backend: 'D3D12', fallbackAllowed: false, timestampQueryRequired: true });
export const R9_KERNEL_ID = 'tdt.ewa.ellipse.phase-correct-parametric-r6.v1';
export const R9_ABI_ID = 'tdt.delta-k-ewa.params.v4';
export const R9_ABI_BYTES = 96;
export const R9_COORDINATE_ID = 'tdt.ewa.source-lattice.pixel-center-v2';
export const R9_AXIAL_FIELD_ID = 'tdt.structure-tensor.axial-coherence-edge.r5.v1';
export const R9_ORACLE_ID = 'tdt.ewa.binary64-oracle.r9.v1';
export const R9_BINARY16_ID = 'tdt.ieee754.binary16.independent.r9.v1';
export const R9_TEST_PARTITION_ID = 'tdt.package.test-partition.resample-r9.v1';
export const R9_ERROR_CODES = Object.freeze([
  'E_R9_PARENT_EVIDENCE_MISMATCH','E_R9_SOURCE_HARNESS_INCOMPLETE','E_R9_PACKAGE_IDENTITY_MISMATCH','E_R9_SOURCE_TREE_LOAD_DETECTED',
  'E_R9_SOFTWARE_ADAPTER','E_R9_D3D12_EVIDENCE_MISSING','E_R9_TIMESTAMP_QUERY_MISSING','E_R9_WGSL_COMPILE','E_R9_PIPELINE_CREATE',
  'E_R9_BIND_LAYOUT','E_R9_PRODUCT_REFERENCE_MISMATCH','E_R9_ORACLE_ULP_EXCEEDED','E_R9_NONFINITE_OUTPUT','E_R9_FAULT_SENTINEL_ADMITTED',
  'E_R9_VALIDATION_COUNTER_NONZERO','E_R9_VALIDATION_COUNTER_DISCONNECTED','E_R9_DC_CONSERVATION','E_R9_ALPHA_IDENTITY',
  'E_R9_BORDER_CONSERVATION','E_R9_PREVIEW_EXPORT_DIVERGENCE','E_R9_TIMESTAMP_INVALID','E_R9_PERFORMANCE_REGRESSION',
  'E_R9_RESIDENCY_GROWTH','E_R9_RESOURCE_LEAK','E_R9_DEVICE_LOSS_TIMEOUT','E_R9_STALE_EPOCH_REUSED','E_R9_POST_RECOVERY_MISMATCH',
  'E_R9_INTERMEDIATE_READBACK','E_R9_PACKAGE_MUTATED','E_R9_CHILD_EVIDENCE_MISSING','E_R9_PENDING_PHYSICAL_GATE',
  'E_R9_PRODUCTION_POINTER_MUTATED'
]);
