import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';
import requirements from './gate-requirements.json' with {type:'json'};
import {ROOT,read,readJson,sha256File,sha256Buffer,stableJson,capture,check,fileExists,sourceSyntaxFiles,productionPointerDigest,writeSourceArtifact} from './lib.mjs';
import {selfTestBinary16} from './oracle/binary16.mjs';
import {rowPaddingNegativeControl} from './comparators/raw-texture-layout.mjs';
import {executeNegativeControls} from './negative-controls/index.mjs';
import {R9_SOURCE_STATE,R9_HARNESS_ID,R9_EVIDENCE_SCHEMA_ID,R9_ERROR_CODES,R9_PRIMARY_PLATFORM} from './identity.mjs';
const packageJson=readJson('package.json'),vite=read('vite.config.ts'),electron=read('electron.mjs'),preload=read('preload.cjs'),guard=read('app/electron/r9-physical-e2e-guard.mjs'),runner=read('app/renderer/physical-r9/physical-runner.mjs'),bridge=read('app/renderer/physical-r9/physical-bridge.mjs'),fixture=readJson('fixtures/resample-runtime-01-r9/R9_FIXTURE_MANIFEST.json'),partition=readJson('tools/resample-runtime-01-r9/package/test-partition-manifest.json'),profile=readJson('tools/resample-runtime-01-r9/package/qualification-profile.json');
const parent=readJson('artifacts/resample-runtime-01-r9/source-bake/TDT_RESAMPLE_RUNTIME_01_R9_PARENT_REPORT.json');
const pointer=productionPointerDigest();
const schemaFiles=fs.readdirSync(path.join(ROOT,'tools/resample-runtime-01-r9/schemas')).filter(x=>x.endsWith('.json')).sort();
const requiredFiles=['app/electron/r9-physical-e2e-guard.mjs','app/renderer/physical-r9/index.html','app/renderer/physical-r9/physical-runner.mjs','app/renderer/physical-r9/physical-bridge.mjs','tools/resample-runtime-01-r9/build-package-candidate.mjs','tools/resample-runtime-01-r9/run-packaged-physical.mjs','tools/resample-runtime-01-r9/finalize-source.mjs','tools/resample-runtime-01-r9/finalize-physical.mjs'];
const checks={
 parent:()=>check(parent.pass,'E_R9_PARENT_EVIDENCE_MISMATCH','parent report failed'),
 schemas:()=>{check(schemaFiles.length>=15,'E_R9_SOURCE_HARNESS_INCOMPLETE','schema set incomplete',{schemaFiles});for(const f of schemaFiles){const s=readJson(`tools/resample-runtime-01-r9/schemas/${f}`);check(s.$schema&&s.type==='object'&&Array.isArray(s.required),'E_R9_SOURCE_HARNESS_INCOMPLETE','schema malformed',{f});}return schemaFiles;},
 files:()=>{for(const f of requiredFiles)check(fileExists(f),'E_R9_SOURCE_HARNESS_INCOMPLETE','required R9 file missing',{f});return requiredFiles;},
 scripts:()=>{for(const n of ['generate:resample-runtime-01-r9','verify:resample-runtime-01-r9:parent','verify:resample-runtime-01-r9:source','build:resample-runtime-01-r9:package','run:resample-runtime-01-r9:physical','verify:resample-runtime-01-r9:physical','finalize:resample-runtime-01-r9:source','finalize:resample-runtime-01-r9:physical','verify:resample-runtime-01-r9'])check(typeof packageJson.scripts?.[n]==='string','E_R9_SOURCE_HARNESS_INCOMPLETE','package script missing',{n});return true;},
 syntax:()=>{const failures=[];for(const rel of sourceSyntaxFiles()){const r=spawnSync(process.execPath,['--check',path.join(ROOT,rel)],{encoding:'utf8'});if(r.status!==0)failures.push({rel,output:`${r.stdout}${r.stderr}`});}check(failures.length===0,'E_R9_SOURCE_HARNESS_INCOMPLETE','R9 source syntax failure',failures);return{fileCount:sourceSyntaxFiles().length};},
 fixture:()=>{const base={...fixture};delete base.fixtureDigest;check(fixture.fixtureDigest===sha256Buffer(stableJson(base)),'E_R9_SOURCE_HARNESS_INCOMPLETE','fixture digest mismatch');check(fixture.fixtures.length===24,'E_R9_SOURCE_HARNESS_INCOMPLETE','fixture count mismatch');return{count:fixture.fixtures.length,digest:fixture.fixtureDigest};},
 binary16:()=>selfTestBinary16(),
 negative:()=>{const r=executeNegativeControls();check(r.pass,'E_R9_SOURCE_HARNESS_INCOMPLETE','negative controls incomplete',r);return r;},
 padding:()=>check(rowPaddingNegativeControl(),'E_R9_SOURCE_HARNESS_INCOMPLETE','row padding negative control failed'),
 packageGuard:()=>{for(const token of ['app.isPackaged','E_R9_SOURCE_TREE_LOAD_DETECTED','E_R9_PACKAGE_MUTATED','singleRunLock','interruptionMarker','networkPolicy'])check(guard.includes(token),'E_R9_SOURCE_HARNESS_INCOMPLETE','guard token missing',{token});return true;},
 electronWiring:()=>{for(const token of ['DADUM_R9_PHYSICAL_MODE','createR9PhysicalGuard','createR9PhysicalWindow','dadum:r9-launch-context','dadum:r9-write-artifact','dadum:r9-complete'])check(electron.includes(token),'E_R9_SOURCE_HARNESS_INCOMPLETE','electron R9 wiring missing',{token});check(preload.includes('r9Physical'),'E_R9_SOURCE_HARNESS_INCOMPLETE','preload R9 bridge missing');return true;},
 renderer:()=>{for(const token of ['GpuDeviceAuthorityService','timestamp-query','compareRawBinary16','evaluateR9Oracle','R9_PHYSICAL_ASSERTIONS.json','runDeviceLossSuite','runTimestampSuite','runResidencySuite','executeCanonicalEwaLowpassR8'])check(runner.includes(token),'E_R9_SOURCE_HARNESS_INCOMPLETE','physical runner token missing',{token});return true;},
 testPartition:()=>{check(partition.productionAuthority===false&&partition.devServerAllowed===false&&partition.sourceTreeAccess===false,'E_R9_SOURCE_HARNESS_INCOMPLETE','test partition unsafe',partition);check(vite.includes('physical-r9/index.html'),'E_R9_SOURCE_HARNESS_INCOMPLETE','Vite physical entry missing');return partition;},
 platform:()=>{check(profile.platform===R9_PRIMARY_PLATFORM.platform&&profile.arch===R9_PRIMARY_PLATFORM.arch&&profile.backend===R9_PRIMARY_PLATFORM.backend,'E_R9_SOURCE_HARNESS_INCOMPLETE','qualification profile mismatch');return profile;},
 noDev:()=>{check(guard.includes('DADUM_VITE_DEV_SERVER_URL')&&guard.includes('E_R9_SOURCE_TREE_LOAD_DETECTED'),'E_R9_SOURCE_HARNESS_INCOMPLETE','dev server rejection missing');return true;},
 isolation:()=>{check(guard.includes('app.isPackaged')&&guard.includes('sourceTreeIsolated'),'E_R9_SOURCE_HARNESS_INCOMPLETE','package isolation proof missing');return true;},
 oracleTestOnly:()=>{const productFiles=['app/legacy-runtime/core/compute/qmap_webgpu/ewa_canonical_lowpass_runtime_r8.mjs','app/legacy-runtime/core/compute/qmap_webgpu/ewa_aniso_tile.mjs'];for(const f of productFiles)check(!read(f).includes('resample-runtime-01-r9/oracle'),'E_R9_SOURCE_HARNESS_INCOMPLETE','oracle imported by product',{f});return true;},
 validationTestOnly:()=>{check(!read('app/legacy-runtime/core/compute/qmap_webgpu/ewa_canonical_lowpass_runtime_r8.mjs').includes('validationR4'),'E_R9_SOURCE_HARNESS_INCOMPLETE','validation path entered product runtime');return true;},
 noCpuFallback:()=>{check(!runner.includes('canvas.getContext(\'2d\')')&&!runner.includes('webgl'),'E_R9_SOURCE_HARNESS_INCOMPLETE','forbidden graphics fallback token');return true;},
 errors:()=>{for(const code of R9_ERROR_CODES)check(read('tools/resample-runtime-01-r9/identity.mjs').includes(code),'E_R9_SOURCE_HARNESS_INCOMPLETE','stable error code missing',{code});return R9_ERROR_CODES.length;},
 pointer:()=>pointer,
 noPromotion:()=>{for(const f of ['tools/resample-runtime-01-r9/finalize-source.mjs','tools/resample-runtime-01-r9/finalize-physical.mjs'])check(!read(f).includes('update-promotion-pointer-cas'),'E_R9_PRODUCTION_POINTER_MUTATED','R9 promotion call forbidden',{f});return true;},
 identities:()=>{check(read('tools/resample-runtime-01-r9/identity.mjs').includes(R9_HARNESS_ID)&&read('tools/resample-runtime-01-r9/identity.mjs').includes(R9_EVIDENCE_SCHEMA_ID),'E_R9_SOURCE_HARNESS_INCOMPLETE','identity missing');return true;},
 sourceState:()=>R9_SOURCE_STATE,
 physicalPending:()=>{const t=read('tools/resample-runtime-01-r9/finalize-source.mjs');check(t.includes("status:'PENDING'")&&!t.includes("physicalGpuExecuted:true"),'E_R9_SOURCE_HARNESS_INCOMPLETE','source finalizer could claim physical pass');return true;},
 packageHash:()=>{check(guard.includes('packageDigestBefore')&&guard.includes('packageDigestAfter'),'E_R9_SOURCE_HARNESS_INCOMPLETE','package before/after hash missing');return true;},
 samePackage:()=>{const launcher=read('tools/resample-runtime-01-r9/run-packaged-physical.mjs'),builder=read('tools/resample-runtime-01-r9/build-package-candidate.mjs');check(guard.includes('packageDigestBefore')&&guard.includes('packageDigestAfter')&&guard.includes('evidenceRoot'),'E_R9_SOURCE_HARNESS_INCOMPLETE','package before/after or external evidence guard missing');check(runner.includes('runCanonicalPreviewExport(authorityCtx)')&&runner.includes('const device=authorityCtx.device'),'E_R9_SOURCE_HARNESS_INCOMPLETE','Preview and Export do not share the authority device');check(!launcher.includes('--disable-gpu')&&!launcher.includes('swiftshader')&&!launcher.includes('forceFallback'),'E_R9_SOURCE_HARNESS_INCOMPLETE','GPU downgrade flag present');check(builder.includes("'release','win-unpacked'")&&builder.includes('DadumDadum.exe'),'E_R9_SOURCE_HARNESS_INCOMPLETE','unpacked package qualification missing');return true;},
 timestamp:()=>{check(runner.includes('GPUQuerySet')||runner.includes('createQuerySet'),'E_R9_SOURCE_HARNESS_INCOMPLETE','timestamp query implementation missing');check(!runner.includes('Date.now() /'),'E_R9_SOURCE_HARNESS_INCOMPLETE','wall clock timing substitution detected');return true;},
 residency:()=>{for(const token of ['ResourceLedger','rendererMemory','gpuProcessMemory','robustSlope'])check(runner.includes(token),'E_R9_SOURCE_HARNESS_INCOMPLETE','residency token missing',{token});return true;},
 loss:()=>{for(const token of ['device.destroy','staleLease','threeLossCycles','deviceEpoch'])check(runner.includes(token),'E_R9_SOURCE_HARNESS_INCOMPLETE','device loss token missing',{token});return true;},
 packageExecution:()=>{for(const token of ['consumerEnvelope:\'preview\'','consumerEnvelope:\'export\'','terminalReadbackCount'])check(runner.includes(token),'E_R9_SOURCE_HARNESS_INCOMPLETE','package execution token missing',{token});return true;},
 rawLayout:()=>{const c=read('tools/resample-runtime-01-r9/comparators/raw-texture-layout.mjs');for(const token of ['alignedBytesPerRow','stripTexturePadding','compareRawBinary16','binary16UlpDistance'])check(c.includes(token),'E_R9_SOURCE_HARNESS_INCOMPLETE','raw layout comparator incomplete',{token});return true;},
 f64Reuse:()=>{const o=read('tools/resample-runtime-01-r9/oracle/f64-ewa-oracle-r9.mjs');check(o.includes("../../resample-runtime-01-r3/ewa-f64-oracle.mjs"),'E_R9_SOURCE_HARNESS_INCOMPLETE','R3 oracle primitives not reused');return true;},
 schemasCount:()=>schemaFiles.length,
 cleanup:()=>{check(guard.includes('cleanupLedger')&&runner.includes('cleanupLedger'),'E_R9_SOURCE_HARNESS_INCOMPLETE','cleanup ledger missing');return true;},
 lock:()=>{check(guard.includes("'wx'")||guard.includes('wx'),'E_R9_SOURCE_HARNESS_INCOMPLETE','single run lock not exclusive');return true;},
 network:()=>{check(guard.includes('127.0.0.1')&&guard.includes('onBeforeRequest'),'E_R9_SOURCE_HARNESS_INCOMPLETE','loopback network policy missing');return true;},
 output:()=>{check(guard.includes('E_R9_OUTPUT_EXISTS')&&guard.includes('path.resolve'),'E_R9_SOURCE_HARNESS_INCOMPLETE','output overwrite/root guard missing');return true;},
 finalReceipt:()=>{check(read('tools/resample-runtime-01-r9/finalize-physical.mjs').includes('NO_PENDING_PHYSICAL_GATE'),'E_R9_SOURCE_HARNESS_INCOMPLETE','physical finalizer pending rejection missing');return true;},
 next:()=>{check(read('tools/resample-runtime-01-r9/finalize-source.mjs').includes('TDT-RESAMPLE-RUNTIME-01-R10'),'E_R9_SOURCE_HARNESS_INCOMPLETE','next authority missing');return true;}
};
const map={};
for(const row of requirements.sourceMandatory){const n=row.requirement;let key='files';
 if(row.id<='R9-S015')key='parent';else if(/SCHEMA/.test(n))key='schemas';else if(/HARNESS_IDENTITY|EVIDENCE_SCHEMA/.test(n))key='identities';else if(/SCRIPT_ENTRYPOINTS/.test(n))key='scripts';else if(/SOURCE_SYNTAX/.test(n))key='syntax';else if(/FIXTURE/.test(n))key='fixture';else if(/F64_ORACLE/.test(n))key='f64Reuse';else if(/BINARY16/.test(n))key='binary16';else if(/RAW_TEXTURE_LAYOUT|SIGNED_ZERO|NAN_POLICY|FAULT_SENTINEL|EXACT_RULE|ULP_RULE/.test(n))key='rawLayout';else if(/NEGATIVE_CONTROL|ROW_PADDING|CHANNEL_ORDER|ENDIAN/.test(n))key='negative';else if(/PHYSICAL_RUNNER|RENDERER_HARNESS|TEST_ONLY_BRIDGE/.test(n))key='renderer';else if(/ELECTRON_MAIN_GUARD/.test(n))key='electronWiring';else if(/NO_DEV_SERVER/.test(n))key='noDev';else if(/NO_SOURCE_TREE_READ/.test(n))key='isolation';else if(/NO_REFERENCE_AS_PRODUCT|NO_CPU_RUNTIME_FALLBACK/.test(n))key='noCpuFallback';else if(/ORACLE_TEST_ONLY/.test(n))key='oracleTestOnly';else if(/VALIDATION_SHADER_TEST_ONLY/.test(n))key='validationTestOnly';else if(/NEGATIVE_CONTROL_TEST_ONLY|ACTIVE_GRAPH_ADMISSION|PACKAGE_CONTENT_ADMISSION/.test(n))key='testPartition';else if(/NETWORK_DISABLED/.test(n))key='network';else if(/WINDOWS_PATH_SAFETY|OUTPUT_OVERWRITE_GUARD/.test(n))key='output';else if(/SINGLE_RUN_LOCK/.test(n))key='lock';else if(/INTERRUPTION_MARKER|CLEANUP_LEDGER/.test(n))key='cleanup';else if(/PRIMARY_PLATFORM|ELECTRON_VERSION|CHROMIUM_VERSION|NODE_VERSION|D3D12|SOFTWARE_ADAPTER|DISCRETE_ADAPTER|TIMESTAMP_FEATURE|REQUIRED_LIMITS|FEATURE_LIMIT|POWER_STATE|DISPLAY_STATE/.test(n))key='platform';else if(/PACKAGE_BUILD_REPRODUCIBLE|PACKAGE_HASH/.test(n))key='packageHash';else if(/EVIDENCE_EXTERNAL|SAME_PACKAGE|SAME_DEVICE|NO_GPU_FLAG|UNPACKED_PACKAGE/.test(n))key='samePackage';else if(/TIMESTAMP_FAKE/.test(n))key='timestamp';else if(/RESIDENCY_LEDGER/.test(n))key='residency';else if(/STALE_EPOCH/.test(n))key='loss';else if(/STABLE_ERROR_CODES/.test(n))key='errors';else if(/PRODUCTION_POINTER/.test(n))key='pointer';else if(/R8_PREDECESSOR/.test(n))key='parent';else if(/SOURCE_GRAPH|SOURCE_DETERMINISM|SOURCE_RECEIPT_COMPLETE/.test(n))key='files';else if(/SOURCE_STATE/.test(n))key='sourceState';else if(/NO_PHYSICAL_PASS|NO_FINAL_STATE_WITH_PENDING/.test(n))key='physicalPending';else if(/NO_PRODUCTION_PROMOTION/.test(n))key='noPromotion';else if(/NEXT_AUTHORITY/.test(n))key='next';map[row.id]=key;}
const cache=new Map();const gateResults=requirements.sourceMandatory.map(row=>{const key=map[row.id];if(!cache.has(key))cache.set(key,capture(key,checks[key]));const c=cache.get(key);return{id:row.id,requirement:row.requirement,status:c.status,evidenceKey:key,evidence:c.evidence??null,errorCode:c.errorCode??null,message:c.message??null};});
const pass=gateResults.every(g=>g.status==='PASS');const report={schemaVersion:1,patchId:'TDT-RESAMPLE-RUNTIME-01-R9',harnessId:R9_HARNESS_ID,evidenceSchemaId:R9_EVIDENCE_SCHEMA_ID,state:pass?R9_SOURCE_STATE:'RESAMPLE_RUNTIME_R9_SOURCE_HARNESS_REJECTED',pass,counts:{PASS:gateResults.filter(x=>x.status==='PASS').length,FAIL:gateResults.filter(x=>x.status==='FAIL').length},gateResults,sourceEvidence:[...cache.entries()].map(([key,value])=>({key,...value})),productionPointerDigestBefore:pointer.digest};writeSourceArtifact('TDT_RESAMPLE_RUNTIME_01_R9_SOURCE_GATE_REPORT.json',report);if(!pass){console.error(JSON.stringify(report,null,2));process.exit(1);}console.log(`R9 source gates ${report.counts.PASS} PASS / ${report.counts.FAIL} FAIL`);
