import fs from 'node:fs';import {fileURLToPath} from 'node:url';import {writeJson,check} from './lib.mjs';
globalThis.crypto ??= (await import('node:crypto')).webcrypto;
globalThis.GPUShaderStage={COMPUTE:4};globalThis.GPUBufferUsage={UNIFORM:64,COPY_DST:8,STORAGE:128,COPY_SRC:4,MAP_READ:1};globalThis.GPUTextureUsage={COPY_SRC:1,COPY_DST:2,TEXTURE_BINDING:4,STORAGE_BINDING:8};globalThis.GPUMapMode={READ:1};
globalThis.fetch=async url=>{const u=url instanceof URL?url:new URL(String(url));const text=fs.readFileSync(fileURLToPath(u),'utf8');return {ok:true,status:200,text:async()=>text};};
let pipelineSeq=0,submitCount=0,destroyCount=0;function texture(label='tex'){return {label,width:64,height:64,createView(){return {texture:this};},destroy(){destroyCount++;}};}function buffer(desc){let bytes=new ArrayBuffer(desc.size);return {desc,destroy(){destroyCount++;},mapAsync:async()=>{},getMappedRange:()=>bytes,unmap(){},_set(v){bytes=v.buffer.slice(v.byteOffset,v.byteOffset+v.byteLength);}};}
const device={features:new Set(),limits:{maxComputeWorkgroupStorageSize:32768},queue:{writeBuffer(target,off,data){if(target?._set)target._set(new Uint8Array(data));},submit(){submitCount++;},onSubmittedWorkDone:async()=>{}},createShaderModule(d){return {d,getCompilationInfo:async()=>({messages:[]})};},createBindGroupLayout:d=>({d}),createPipelineLayout:d=>({d}),createComputePipeline(d){return {id:++pipelineSeq,d,getBindGroupLayout(){return d.layout?.d?.bindGroupLayouts?.[0]??{};}};},createBuffer:buffer,createTexture:d=>texture(d.label),createBindGroup:d=>({d}),createCommandEncoder(){return {beginComputePass(){return {setPipeline(){},setBindGroup(){},dispatchWorkgroups(){},end(){}};},copyBufferToBuffer(){},finish(){return {};}};}};
globalThis.__DADUM_GPU_AUTHORITY_BRIDGE__={getCurrentIdentity:()=>({state:'ACTIVE',runtimeEpoch:1,deviceEpoch:2,deviceIdentity:'mock-device',admittedFeatures:[]}),createShaderModule:(o,i,d)=>device.createShaderModule(d),createComputePipeline:(o,i,d)=>device.createComputePipeline(d),acquireLease:async()=>({device,runtimeEpoch:1,deviceEpoch:2,deviceIdentity:'mock-device',assertCurrent(){},release(){}}),registerRecoveryParticipant(){return ()=>{};}};
const {registerEwaTextureMetadata}=await import('../../app/legacy-runtime/core/compute/qmap_webgpu/ewa_aniso_contract.mjs');const {selectEwaR2Profile}=await import('../../app/legacy-runtime/core/compute/qmap_webgpu/ewa_tiled_profile_r2.mjs');const {createEWAAnisoPipeline,dispatchEWAAniso}=await import('../../app/legacy-runtime/core/compute/qmap_webgpu/ewa_aniso_tile.mjs');const {runEwaR2PairedTimestampBenchmark}=await import('../../app/legacy-runtime/core/compute/qmap_webgpu/ewa_performance_runtime_r2.mjs');
const checks=[];const r4=selectEwaR2Profile({inW:150,inH:150,outW:100,outH:100,sigmaMain:1.0,sigmaCross:0.5,maxAnisotropy:2,adaptivePolicy:{level0FootprintScale:1,level1FootprintScale:1,level2FootprintScale:1}},device.limits);checks.push(check(r4.profile.key==='R4','SMOKE-01','reach 4 selects R4',r4));const r6=selectEwaR2Profile({inW:200,inH:200,outW:100,outH:100,sigmaMain:1.25,sigmaCross:0.65,maxAnisotropy:3,adaptivePolicy:{level0FootprintScale:1,level1FootprintScale:1,level2FootprintScale:1}},device.limits);checks.push(check(r6.profile.key==='R6','SMOKE-02','reach 5/6 selects R6',r6));let unsupported=false;try{selectEwaR2Profile({inW:400,inH:400,outW:100,outH:100,sigmaMain:2,maxAnisotropy:4,adaptivePolicy:{level0FootprintScale:1.5,level1FootprintScale:1.5,level2FootprintScale:1.5}},device.limits);}catch(e){unsupported=e.code==='E_R2_TILE_COVERAGE_UNPROVEN'||e.code==='E_R2_FOOTPRINT_UNSUPPORTED';}checks.push(check(unsupported,'SMOKE-03','unsupported footprint fail closed'));
const bundle=await createEWAAnisoPipeline(device);checks.push(check(bundle.tiledR4.pipelineIdentity!==bundle.tiledR6.pipelineIdentity,'SMOKE-04','R4/R6 pipeline identities differ'));checks.push(check(bundle.referenceShaderDigest==='4f8a4574ff9ad5fb0f5eeaad5e687e8d83d1639698f4d90ba4c146568d2bfd5b','SMOKE-05','canonical R5 reference digest pinned'));
const axialTexture=texture('tensor');registerEwaTextureMetadata(axialTexture,{width:150,height:150,format:'rgba16float',axialFieldSchemaId:'tdt.structure-tensor.axial-coherence-edge.r5.v1'});const base={srcTex:texture('src'),tensorTex:axialTexture,policyTex:texture('policy'),dstTex:texture('dst'),tensorMode:'canonical-stage-local-r1c',tensorFieldMode:'axial-double-angle-r5',inW:150,inH:150,outW:100,outH:100,sigmaMain:1,sigmaCross:.5,maxAnisotropy:2,edgeLow:.025,edgeHigh:.22,minorCoverageFactor:.82,coherenceExponent:1.25,stageIndex:0,stageCount:1,adaptivePolicy:{level0FootprintScale:1,level1FootprintScale:1,level2FootprintScale:1},jobId:'r2-r4'};const receipt=await dispatchEWAAniso(device,bundle,base);checks.push(check(receipt.profileKey==='R4'&&receipt.strictSharedTile===true&&receipt.productDirectLoadFallback===false,'SMOKE-06','R4 strict dispatch receipt',receipt));const receipt6=await dispatchEWAAniso(device,bundle,{...base,inW:200,inH:200,sigmaMain:1.25,sigmaCross:.65,maxAnisotropy:3,jobId:'r2-r6'});checks.push(check(receipt6.profileKey==='R6','SMOKE-07','R6 dispatch receipt',receipt6));checks.push(check(submitCount===2,'SMOKE-08','one submit per product dispatch',{submitCount}));const perf=await runEwaR2PairedTimestampBenchmark({identity:{admittedFeatures:[]},parityReceipt:{status:'PASS',receiptId:'mock-parity'},profileId:r4.profile.profileId});checks.push(check(perf.status==='DEFERRED'&&perf.reason==='timestamp-query-unavailable','SMOKE-09','timestamp absence defers'));bundle.dispose();checks.push(check(destroyCount>=7,'SMOKE-10','bundle resources disposed',{destroyCount}));const pass=checks.every(c=>c.pass);writeJson('r2-runtime-smoke.json',{schemaVersion:1,patchId:'TDT-RESAMPLE-RUNTIME-01-R2',pass,checks,submitCount,destroyCount});if(!pass){console.error(checks.filter(c=>!c.pass));process.exit(1);}console.log(`PASS R2 mock runtime ${checks.length}/${checks.length}`);
