import crypto from 'node:crypto';
import { createBakemonoRinneFormulaContractReceipt } from '../../app/legacy-runtime/core/compute/qmap_webgpu/bakemono_rinne_contract_receipt.mjs';
import { BKR01_FORMULA_PROFILE_CANONICAL } from '../../app/legacy-runtime/core/compute/qmap_webgpu/bakemono_rinne_formula_contract.mjs';
import { BKR01_TENSOR_ADMISSION_ID } from '../../app/legacy-runtime/core/compute/qmap_webgpu/bakemono_rinne_tensor_admission.mjs';
import { createBakemonoRinneLambda2QualificationReceiptWgsl03 } from '../../app/legacy-runtime/core/compute/qmap_webgpu/bakemono_rinne_wgsl_03_receipt.mjs';
import { recordBakemonoRinneNativeIntegrationWgsl04,createFinalEwaTerminalSurfaceDescriptorWgsl04 } from '../../app/legacy-runtime/core/compute/qmap_webgpu/bakemono_rinne_wgsl_04_integration.mjs';
import { sha256BakemonoRinneWgsl04 } from '../../app/legacy-runtime/core/compute/qmap_webgpu/bakemono_rinne_wgsl_04_receipt.mjs';
import { packTensorR1CParams,normalizeTensorR1CParameters } from '../../app/legacy-runtime/core/compute/qmap_webgpu/structure_tensor_params.mjs';
import { BKR04_LAMBDA2_FIXTURE_CORPUS_DIGEST } from '../../app/legacy-runtime/core/compute/qmap_webgpu/bakemono_rinne_wgsl_04_contract.mjs';

export const hex=(seed)=>crypto.createHash('sha256').update(String(seed)).digest('hex');
export function fakeTexture(label){return {label,createView(){return {label:`view:${label}`};},destroy(){this.destroyed=true;}};}
export function fakeDevice(){let textureCount=0;return {createTexture(d){textureCount+=1;return fakeTexture(d.label??`texture-${textureCount}`);},createBindGroup(d){return {label:d.label??null,entries:d.entries,layout:d.layout};},get textureCount(){return textureCount;}};}
export function fakeGraph(device=fakeDevice(),options={}){let passCount=0,allocationCount=0,submitted=Boolean(options.submitted);const tracked=[];const passes=[];const allocations=[];return {id:options.id??'graph:bkr04-source',device,allocateUniform(payload,metadata={}){allocationCount+=1;const size=payload?.byteLength??payload?.length??0;const row=Object.freeze({buffer:{label:'uniform-ring-buffer'},offset:(allocationCount-1)*256,bindingSize:size,size,slotIndex:allocationCount-1,...metadata});allocations.push(row);return row;},beginComputePass(label){if(submitted)throw Object.assign(new Error('submitted'),{code:'E_R9A_COMMAND_GRAPH_ALREADY_SUBMITTED'});passCount+=1;const row={label,pipeline:null,bindGroup:null,dispatch:null,ended:false};passes.push(row);return {setPipeline(v){row.pipeline=v;},setBindGroup(i,v){row.bindGroup={i,v};},dispatchWorkgroups(x,y,z){row.dispatch=[x,y,z];},end(){row.ended=true;}};},trackTransient(resource){tracked.push(resource);},snapshot(){return Object.freeze({submitted,passCount,uniformRing:Object.freeze({allocationCount}),commandEncoderCount:1,queueSubmitCount:submitted?1:0});},markSubmitted(){submitted=true;},get passCount(){return passCount;},get allocationCount(){return allocationCount;},tracked,passes,allocations};}
export function identity(){return Object.freeze({state:'ACTIVE',runtimeEpoch:7,deviceEpoch:3,deviceIdentity:'device:bkr04',adapterIdentity:'adapter:bkr04'});}
export function tensorBundle(id=identity()){return {disposed:false,runtimeEpoch:id.runtimeEpoch,deviceEpoch:id.deviceEpoch,deviceIdentity:id.deviceIdentity,layout:{label:'tensor-layout'},pipelines:Object.fromEntries(['gradient','outer','blurH','blurV','eigen','axial'].map(k=>[k,{label:`tensor:${k}`}])),shaderDigests:{gradient:hex('gradient'),outer:hex('outer'),blurH:hex('blurH'),blurV:hex('blurV'),eigen:hex('eigen'),axial:hex('axial')},pipelineIdentity:'tdt.structure-tensor.chain.v1:d3'};}
export function effectFamily(id=identity()){return {schemaId:'tdt.pipeline.bakemono-rinne.command-graph-family.wgsl04.v1',ownerId:'dadum.gpu.consumer.bakemono-rinne-wgsl-04',pipelineFamilyId:'tdt.pipeline.bakemono-rinne.command-graph-family.wgsl04.v1',runtimeEpoch:id.runtimeEpoch,deviceEpoch:id.deviceEpoch,deviceIdentity:id.deviceIdentity,kernelId:'tdt.effect.bakemono-rinne.kernel.wgsl.r1c-gated-shadow.v1',kernelAbiId:'tdt.effect.bakemono-rinne.abi.r1c-gated-shadow.v1',generatedWgslDigest:hex('wgsl'),generatorManifestDigest:hex('manifest'),bindGroupLayoutDigest:hex('bgl'),uniformAbiDigest:hex('uniform'),canonicalDeltaDigest:hex('delta'),structureGateSourceDigest:hex('gate'),pipelineIdentity:'tdt.pipeline.bakemono-rinne.command-graph-family.wgsl04.v1:d3',pipelineIdentityDigest:hex('pipeline-identity'),pipeline:{label:'effect-pipeline'},bindGroupLayout:{label:'effect-bgl'},disposed:false,dispose(){this.disposed=true;}};}
export function descriptor(role,width=33,height=31,id=identity(),texture=fakeTexture(role)){return Object.freeze({texture,resourceId:`resource:${role}`,contentDigest:hex(`content:${role}`),semanticId:`tdt.effect.input.${role}.v1`,width,height,format:'r16float',runtimeEpoch:id.runtimeEpoch,deviceEpoch:id.deviceEpoch,deviceIdentity:id.deviceIdentity});}
export async function createFixture(options={}){
 const id=identity(),device=fakeDevice(),graph=fakeGraph(device,options.graphOptions),tensor=tensorBundle(id),family=effectFamily(id),width=options.width??33,height=options.height??31;
 const lowpassReceipt=Object.freeze({receiptDigest:hex('lowpass'),planDigest:hex('plan')});const base=createFinalEwaTerminalSurfaceDescriptorWgsl04({texture:fakeTexture('final-ewa'),width,height,lowpassReceipt,identity:id,commandGraphId:graph.id,surfaceId:'surface:bkr04',surfaceRevision:2});const phaseReceipt=Object.freeze({mode:'STILL_EXPLICIT',wrappedPhaseBase:.25,receiptDigest:hex('phase')});
 const formulaContractReceipt=await createBakemonoRinneFormulaContractReceipt({formulaProfileId:BKR01_FORMULA_PROFILE_CANONICAL,formulaInventoryDigest:hex('inventory'),formulaSourceDigest:hex('formula'),utilitySourceDigest:hex('utility'),colorContractDigest:hex('color'),scalarProfileId:'LEGACY_DELTA_E_COMPAT',scalarProfileDigest:hex('scalar-profile'),maskProfileId:'LEGACY_MASKS',tensorAdmissionId:BKR01_TENSOR_ADMISSION_ID,tensorAdmissionDigest:hex('tensor-admission'),phaseReceiptDigest:phaseReceipt.receiptDigest,parameterDigest:hex('params'),outputAuthority:'CANONICAL_CANDIDATE'});
 const tensorParameters=Object.freeze({tensorSigma:1.15,maxAnisotropy:3,minorCoverageFactor:.82,coherenceExponent:1.25,sourceDomain:'declared-linear'});const p=normalizeTensorR1CParameters(tensorParameters);const packed=packTensorR1CParams({...p,width,height,stageIndex:0,stageCount:1});const tensorParameterDigest=await sha256BakemonoRinneWgsl04([...new Uint8Array(packed)]);const shaderSetDigest=await sha256BakemonoRinneWgsl04(Object.entries(tensor.shaderDigests).sort(([a],[b])=>a.localeCompare(b)));
 const qualificationReceipt=await createBakemonoRinneLambda2QualificationReceiptWgsl03({status:'PHYSICAL_PASS',physicalExecution:true,shaderSetDigest,tensorParameterDigest,pipelineIdentity:tensor.pipelineIdentity,adapterIdentity:id.adapterIdentity,deviceIdentity:id.deviceIdentity,fixtureCorpusDigest:BKR04_LAMBDA2_FIXTURE_CORPUS_DIGEST,probeWgslDigest:hex('probe'),counterLayoutDigest:hex('counter'),fixtureCount:6,cornerLambda2PositivePixelCount:19,junctionLambda2PositivePixelCount:23,straightMeanCoherence:.99,cornerMeanCoherence:.71,junctionMeanCoherence:.63,nonFiniteCount:0,negativeLambdaCount:0,pass:true});
 const resolver={calls:0,async resolve(input){this.calls+=1;for(const key of ['shaderSetDigest','tensorParameterDigest','adapterIdentity','deviceIdentity','fixtureCorpusDigest'])if(String(input[key])!==String(qualificationReceipt[key]))throw Object.assign(new Error(`resolver mismatch:${key}`),{code:'E_BKR04_LAMBDA2_QUALIFICATION_MISMATCH'});if(String(input.tensorPipelineIdentity)!==String(qualificationReceipt.pipelineIdentity))throw Object.assign(new Error('resolver mismatch:tensorPipelineIdentity'),{code:'E_BKR04_LAMBDA2_QUALIFICATION_MISMATCH'});return qualificationReceipt;}};
 const effect={mode:'CANONICAL_SHADOW',purpose:'QUALIFICATION_GRAPH_SHADOW',operationId:'operation:bkr04-source',formulaContractReceipt,phaseReceipt,qmap:descriptor('qmap',width,height,id),scalar:descriptor('scalar',width,height,id),alphaDepth:descriptor('alpha-depth',width,height,id),highlight:descriptor('highlight',width,height,id),maskEdge:descriptor('mask-edge',width,height,id),power:1,neonBoost:1,coherenceExponent:1.25,alphaEpsilon:1e-6,tensorParameters,retainCandidate:options.retainCandidate??true};
 const input={identity:id,pipeBundle:{tensorR1C:tensor,bakemonoRinneWgsl04:family},finalEwaSurface:base,effect,lambda2Resolver:resolver};
 const result=options.execute===false?null:await recordBakemonoRinneNativeIntegrationWgsl04(graph,input);return {id,device,graph,tensor,family,width,height,base,phaseReceipt,formulaContractReceipt,tensorParameters,tensorParameterDigest,shaderSetDigest,qualificationReceipt,resolver,effect,input,result};
}
